// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

// Code generated by tools/generate. DO NOT EDIT.

package jamfprotect

import (
	"context"
	"encoding/json"
	"fmt"
	"maps"
	"time"
)

// MaxAuditLogDays is the maximum date window the API enforces for audit log queries.
const MaxAuditLogDays = 7

// AuditLogDateRange specifies start and end dates for filtering audit logs.
// The SDK enforces a maximum window of MaxAuditLogDays. If the range exceeds this,
// the start date is clamped to MaxAuditLogDays before the end date.
type AuditLogDateRange struct {
	StartDate time.Time
	EndDate   time.Time
}

func auditLogCondition(dateRange *AuditLogDateRange) map[string]any {
	var start, end time.Time
	if dateRange != nil {
		start = dateRange.StartDate
		end = dateRange.EndDate
	} else {
		end = time.Now().UTC()
		start = end.AddDate(0, 0, -MaxAuditLogDays)
	}

	maxStart := end.AddDate(0, 0, -MaxAuditLogDays)
	if start.Before(maxStart) {
		start = maxStart
	}

	return map[string]any{
		"dateRange": map[string]any{
			"startDate": start.Format(time.RFC3339),
			"endDate":   end.Format(time.RFC3339),
		},
	}
}

func (c *Client) fetchAllAuditLogs(ctx context.Context, query string, baseVars map[string]any, resultKey string) ([]AuditLog, error) {
	var allItems []AuditLog
	var prevCursor string

	vars := make(map[string]any, len(baseVars))
	maps.Copy(vars, baseVars)

	for {
		raw := make(map[string]json.RawMessage)
		if err := c.transport.DoGraphQL(ctx, "/app", query, vars, &raw); err != nil {
			return nil, err
		}

		data, ok := raw[resultKey]
		if !ok {
			return nil, fmt.Errorf("response missing expected key %q", resultKey)
		}

		var page struct {
			Items    []AuditLog `json:"items"`
			PageInfo struct {
				Next *string `json:"next"`
			} `json:"pageInfo"`
		}
		if err := json.Unmarshal(data, &page); err != nil {
			return nil, fmt.Errorf("decoding %s: %w", resultKey, err)
		}

		allItems = append(allItems, page.Items...)

		if page.PageInfo.Next == nil {
			break
		}
		if *page.PageInfo.Next == prevCursor {
			break
		}
		prevCursor = *page.PageInfo.Next
		vars["next"] = *page.PageInfo.Next
	}

	return allItems, nil
}
