// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

// Code generated by tools/generate. DO NOT EDIT.

package jamfprotect

import (
	"context"
	"net/http"
	"time"
)

// Logger is an interface for logging HTTP requests and responses. Bodies are
// copies with the Authorization header, client secrets, API client passwords,
// data-forwarding keys, enrolment material, URLs and webhook header values
// replaced by "[REDACTED]". Other tenant data is passed through unchanged.
type Logger interface {
	LogRequest(ctx context.Context, method, url string, headers http.Header, body []byte)
	LogResponse(ctx context.Context, statusCode int, headers http.Header, body []byte)
}

// TokenCache persists OAuth2 tokens across process restarts.
type TokenCache interface {
	Load(key string) (token string, expiresAt time.Time, ok bool)
	Store(key string, token string, expiresAt time.Time) error
}

// Token holds an access token and its metadata.
type Token struct {
	AccessToken string
	TokenType   string
	Expiry      time.Time
}
