// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

// Code generated by tools/generate. DO NOT EDIT.

package jamfprotect

import (
	"context"
	"fmt"

	"github.com/Jamf-Concepts/jamfprotect-go-sdk/internal/client"
)

// ── Query/Mutation constants ──────────────────────────────────────────────────

const actionConfigFields = `
fragment ActionConfigFields on ActionConfigs {
	id
	name
	description
	hash
	created
	updated
	alertConfig {
		data {
			binary {
				attrs
				related
			}
			clickEvent {
				attrs
				related
			}
			downloadEvent {
				attrs
				related
			}
			file {
				attrs
				related
			}
			fsEvent {
				attrs
				related
			}
			group {
				attrs
				related
			}
			procEvent {
				attrs
				related
			}
			process {
				attrs
				related
			}
			screenshotEvent {
				attrs
				related
			}
			usbEvent {
				attrs
				related
			}
			user {
				attrs
				related
			}
			gkEvent {
				attrs
				related
			}
			keylogRegisterEvent {
				attrs
				related
			}
			mrtEvent {
				attrs
				related
			}
		}
	}
	clients {
		id
		type
		supportedReports
		batchConfig {
			sizeIndex
			windowInSeconds
			sizeInBytes
			delimiter
		}
		params {
			... on HttpClientParams {
				headers {
					header
					value
				}
				method
				url
			}
			... on JamfCloudClientParams {
				destinationFilter
			}
			... on KafkaClientParams {
				host
				port
				topic
				clientCN
				serverCN
			}
			... on LogFileClientParams {
				path
				permissions
				maxSizeMB
				ownership
				backups
			}
			... on SyslogClientParams {
				host
				port
				scheme
			}
		}
	}
	plans {
		id
		name
	}
}
`

const createActionConfigMutation = `
mutation createActionConfigs($name: String!, $description: String!, $clients: [ReportClientInput!], $alertConfig: ActionConfigsAlertConfigInput) {
	createActionConfigs(
		input: {name: $name, description: $description, clients: $clients, alertConfig: $alertConfig}
	) {
		...ActionConfigFields
	}
}
` + actionConfigFields

const getActionConfigQuery = `
query getActionConfigs($id: ID!) {
	getActionConfigs(id: $id) {
		...ActionConfigFields
	}
}
` + actionConfigFields

const updateActionConfigMutation = `
mutation updateActionConfigs($id: ID!, $name: String!, $description: String!, $clients: [ReportClientInput!], $alertConfig: ActionConfigsAlertConfigInput) {
	updateActionConfigs(
		id: $id
		input: {name: $name, description: $description, clients: $clients, alertConfig: $alertConfig}
	) {
		...ActionConfigFields
	}
}
` + actionConfigFields

const deleteActionConfigMutation = `
mutation deleteActionConfigs($id: ID!) {
	deleteActionConfigs(id: $id) {
		id
	}
}
`

const listActionConfigsQuery = `
query listActionConfigs($nextToken: String, $direction: OrderDirection!, $field: ActionConfigsOrderField!, $pageSize: Int) {
	listActionConfigs(
		input: {next: $nextToken, order: {direction: $direction, field: $field}, pageSize: $pageSize}
	) {
		items {
			id
			name
			description
			created
			updated
		}
		pageInfo {
			next
			total
		}
	}
}
`

// ── Input types ───────────────────────────────────────────────────────────────

// ActionConfigInput is the input for actionConfig operations.
type ActionConfigInput struct {
	Name        string
	Description string
	Clients     []map[string]any
	AlertConfig map[string]any
}

// ── Response types ────────────────────────────────────────────────────────────

// AlertConfig contains ActionConfigsAlertConfig data.
type AlertConfig struct {
	Data *AlertData `json:"data"`
}

// ReportClient contains ReportClient data.
type ReportClient struct {
	ID               string             `json:"id"`
	Type             string             `json:"type"`
	SupportedReports []string           `json:"supportedReports"`
	BatchConfig      *BatchConfig       `json:"batchConfig"`
	Params           ReportClientParams `json:"params"`
}

// ReportClientParams contains ReportClientParams data.
type ReportClientParams struct {
	Headers           []ReportClientHeader `json:"headers"`
	Method            string               `json:"method"`
	URL               string               `json:"url"`
	DestinationFilter string               `json:"destinationFilter"`
	Host              string               `json:"host"`
	Port              int64                `json:"port"`
	Topic             string               `json:"topic"`
	ClientCN          string               `json:"clientCN"`
	ServerCN          string               `json:"serverCN"`
	Path              string               `json:"path"`
	Permissions       string               `json:"permissions"`
	MaxSizeMB         int64                `json:"maxSizeMB"`
	Ownership         string               `json:"ownership"`
	Backups           int64                `json:"backups"`
	Scheme            string               `json:"scheme"`
}

// ActionConfigPlan contains Plan data.
type ActionConfigPlan struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// AlertData contains AlertDataConfigs data.
type AlertData struct {
	Binary              *AlertEventType `json:"binary"`
	ClickEvent          *AlertEventType `json:"clickEvent"`
	DownloadEvent       *AlertEventType `json:"downloadEvent"`
	File                *AlertEventType `json:"file"`
	FsEvent             *AlertEventType `json:"fsEvent"`
	Group               *AlertEventType `json:"group"`
	ProcEvent           *AlertEventType `json:"procEvent"`
	Process             *AlertEventType `json:"process"`
	ScreenshotEvent     *AlertEventType `json:"screenshotEvent"`
	USBEvent            *AlertEventType `json:"usbEvent"`
	User                *AlertEventType `json:"user"`
	GkEvent             *AlertEventType `json:"gkEvent"`
	KeylogRegisterEvent *AlertEventType `json:"keylogRegisterEvent"`
	MrtEvent            *AlertEventType `json:"mrtEvent"`
}

// BatchConfig contains BatchConfig data.
type BatchConfig struct {
	SizeIndex       int64  `json:"sizeIndex"`
	WindowInSeconds int64  `json:"windowInSeconds"`
	SizeInBytes     int64  `json:"sizeInBytes"`
	Delimiter       string `json:"delimiter"`
}

// ReportClientHeader contains HttpHeader data.
type ReportClientHeader struct {
	Header string `json:"header"`
	Value  string `json:"value"`
}

// AlertEventType contains AlertDataConfig data.
type AlertEventType struct {
	Attrs   []string `json:"attrs"`
	Related []string `json:"related"`
}

// ActionConfigListItem contains ActionConfigs data.
type ActionConfigListItem struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Created     string `json:"created"`
	Updated     string `json:"updated"`
}

// ActionConfig represents a Jamf Protect actionConfig.
type ActionConfig struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Hash        string             `json:"hash"`
	Created     string             `json:"created"`
	Updated     string             `json:"updated"`
	AlertConfig *AlertConfig       `json:"alertConfig"`
	Clients     []ReportClient     `json:"clients"`
	Plans       []ActionConfigPlan `json:"plans"`
}

// ── Client methods ────────────────────────────────────────────────────────────

// CreateActionConfig creates a new actionConfig.
func (c *Client) CreateActionConfig(ctx context.Context, input ActionConfigInput) (ActionConfig, error) {
	vars := buildActionConfigVariables(input)
	var result struct {
		CreateActionConfig ActionConfig `json:"createActionConfigs"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", createActionConfigMutation, vars, &result); err != nil {
		return ActionConfig{}, fmt.Errorf("CreateActionConfig: %w", err)
	}
	return result.CreateActionConfig, nil
}

// GetActionConfig retrieves a actionConfig by ID.
func (c *Client) GetActionConfig(ctx context.Context, id string) (*ActionConfig, error) {
	vars := map[string]any{"id": id}
	var result struct {
		GetActionConfig *ActionConfig `json:"getActionConfigs"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", getActionConfigQuery, vars, &result); err != nil {
		return nil, fmt.Errorf("GetActionConfig(%s): %w", id, err)
	}
	return result.GetActionConfig, nil
}

// UpdateActionConfig updates an existing actionConfig.
func (c *Client) UpdateActionConfig(ctx context.Context, id string, input ActionConfigInput) (ActionConfig, error) {
	vars := buildActionConfigVariables(input)
	vars["id"] = id
	var result struct {
		UpdateActionConfig ActionConfig `json:"updateActionConfigs"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", updateActionConfigMutation, vars, &result); err != nil {
		return ActionConfig{}, fmt.Errorf("UpdateActionConfig(%s): %w", id, err)
	}
	return result.UpdateActionConfig, nil
}

// DeleteActionConfig deletes a actionConfig by ID.
func (c *Client) DeleteActionConfig(ctx context.Context, id string) error {
	vars := map[string]any{"id": id}
	if err := c.transport.DoGraphQL(ctx, "/app", deleteActionConfigMutation, vars, nil); err != nil {
		return fmt.Errorf("DeleteActionConfig(%s): %w", id, err)
	}
	return nil
}

// ListActionConfigs retrieves all actionConfigListItems.
func (c *Client) ListActionConfigs(ctx context.Context) ([]ActionConfigListItem, error) {
	actionConfigListItems, err := client.ListAll[ActionConfigListItem](ctx, c.transport, "/app", listActionConfigsQuery, map[string]any{
		"direction": "DESC",
		"field":     "created",
		"pageSize":  100,
	}, "listActionConfigs")
	if err != nil {
		return nil, fmt.Errorf("ListActionConfigs: %w", err)
	}
	return actionConfigListItems, nil
}

func buildActionConfigVariables(input ActionConfigInput) map[string]any {
	return map[string]any{
		"name":        input.Name,
		"description": input.Description,
		"clients":     input.Clients,
		"alertConfig": input.AlertConfig,
	}
}
