// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

// Code generated by tools/generate. DO NOT EDIT.

package jamfprotect

import (
	"context"
	"fmt"
)

// ── Query/Mutation constants ──────────────────────────────────────────────────

const alertStatusCountsFields = `
fragment AlertStatusCountsFields on AlertStatusCountResponse {
	New
	InProgress
	Resolved
	AutoResolved
}
`

const getAlertStatusCountsQuery = `
query getAlertStatusCounts {
	getAlertStatusCounts {
		...AlertStatusCountsFields
	}
}
` + alertStatusCountsFields

// ── Input types ───────────────────────────────────────────────────────────────

// ── Response types ────────────────────────────────────────────────────────────

// AlertStatusCounts represents a Jamf Protect alertStatusCounts.
type AlertStatusCounts struct {
	New          int64 `json:"New"`
	InProgress   int64 `json:"InProgress"`
	Resolved     int64 `json:"Resolved"`
	AutoResolved int64 `json:"AutoResolved"`
}

// ── Client methods ────────────────────────────────────────────────────────────

// GetAlertStatusCounts retrieves the alertStatusCounts.
func (c *Client) GetAlertStatusCounts(ctx context.Context) (AlertStatusCounts, error) {
	var result struct {
		GetAlertStatusCounts AlertStatusCounts `json:"getAlertStatusCounts"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", getAlertStatusCountsQuery, nil, &result); err != nil {
		return AlertStatusCounts{}, fmt.Errorf("GetAlertStatusCounts: %w", err)
	}
	return result.GetAlertStatusCounts, nil
}
