// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

// Code generated by tools/generate. DO NOT EDIT.

package jamfprotect

import (
	"context"
	"fmt"

	"github.com/Jamf-Concepts/jamfprotect-go-sdk/internal/client"
)

// ── Query/Mutation constants ──────────────────────────────────────────────────

const alertFields = `
fragment AlertFields on Alert {
	uuid
	created
	updated
	received
	eventTimestamp
	status
	severity
	actions
	tags
	eventType
	plan {
		uuid
		name
	}
	computer {
		uuid
		hostName
		modelName
		plan {
			id
			name
		}
	}
	analytics {
		name
		label
		description
		uuid
	}
	facts {
		name
		tags
		human
		severity
		matchReason
		actions {
			name
		}
	}
}
`

const getAlertQuery = `
query getAlert($uuid: ID!) {
	getAlert(uuid: $uuid) {
		...AlertFields
	}
}
` + alertFields

const listAlertsQuery = `
query listAlerts($nextToken: String, $direction: OrderDirection!, $field: AlertOrderField!, $pageSize: Int, $filter: AlertFiltersInput) {
	listAlerts(
		input: {next: $nextToken, order: {direction: $direction, field: $field}, pageSize: $pageSize, filter: $filter}
	) {
		items {
			...AlertFields
		}
		pageInfo {
			next
			total
		}
	}
}
` + alertFields

const updateAlertsMutation = `
mutation updateAlerts($uuids: [ID!]!, $status: ALERT_STATUS!) {
	updateAlerts(input: {uuids: $uuids, status: $status}) {
		items {
			...AlertFields
		}
	}
}
` + alertFields

// ── Input types ───────────────────────────────────────────────────────────────

// AlertUpdateInput is the input for alertUpdate operations.
type AlertUpdateInput struct {
	UUIDs  []string
	Status string
}

// ── Response types ────────────────────────────────────────────────────────────

// AlertPlan contains Plan data.
type AlertPlan struct {
	UUID string `json:"uuid"`
	Name string `json:"name"`
}

// AlertComputer contains Computer data.
type AlertComputer struct {
	UUID      string             `json:"uuid"`
	HostName  string             `json:"hostName"`
	ModelName string             `json:"modelName"`
	Plan      *AlertComputerPlan `json:"plan"`
}

// AlertAnalytic contains Analytic data.
type AlertAnalytic struct {
	Name        string `json:"name"`
	Label       string `json:"label"`
	Description string `json:"description"`
	UUID        string `json:"uuid"`
}

// AlertFact contains AlertFact data.
type AlertFact struct {
	Name        string        `json:"name"`
	Tags        []string      `json:"tags"`
	Human       string        `json:"human"`
	Severity    string        `json:"severity"`
	MatchReason string        `json:"matchReason"`
	Actions     []AlertAction `json:"actions"`
}

// AlertComputerPlan contains Plan data.
type AlertComputerPlan struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// AlertAction contains AlertAction data.
type AlertAction struct {
	Name string `json:"name"`
}

// Alert represents a Jamf Protect alert.
type Alert struct {
	UUID           string          `json:"uuid"`
	Created        string          `json:"created"`
	Updated        string          `json:"updated"`
	Received       string          `json:"received"`
	EventTimestamp string          `json:"eventTimestamp"`
	Status         string          `json:"status"`
	Severity       string          `json:"severity"`
	Actions        []string        `json:"actions"`
	Tags           []string        `json:"tags"`
	EventType      string          `json:"eventType"`
	Plan           *AlertPlan      `json:"plan"`
	Computer       *AlertComputer  `json:"computer"`
	Analytics      []AlertAnalytic `json:"analytics"`
	Facts          []AlertFact     `json:"facts"`
}

// ── Client methods ────────────────────────────────────────────────────────────

// GetAlert retrieves a alert by ID.
func (c *Client) GetAlert(ctx context.Context, uuid string) (*Alert, error) {
	vars := map[string]any{"uuid": uuid}
	var result struct {
		GetAlert *Alert `json:"getAlert"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", getAlertQuery, vars, &result); err != nil {
		return nil, fmt.Errorf("GetAlert(%s): %w", uuid, err)
	}
	return result.GetAlert, nil
}

// ListAlerts retrieves all alerts.
func (c *Client) ListAlerts(ctx context.Context) ([]Alert, error) {
	alerts, err := client.ListAll[Alert](ctx, c.transport, "/app", listAlertsQuery, map[string]any{
		"direction": "DESC",
		"field":     "created",
		"filter":    map[string]any{},
	}, "listAlerts")
	if err != nil {
		return nil, fmt.Errorf("ListAlerts: %w", err)
	}
	return alerts, nil
}

// UpdateAlerts bulk-updates alerts.
func (c *Client) UpdateAlerts(ctx context.Context, input AlertUpdateInput) ([]Alert, error) {
	vars := buildAlertUpdateVariables(input)
	var result struct {
		UpdateAlerts struct {
			Items []Alert `json:"items"`
		} `json:"updateAlerts"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", updateAlertsMutation, vars, &result); err != nil {
		return nil, fmt.Errorf("UpdateAlerts: %w", err)
	}
	return result.UpdateAlerts.Items, nil
}

func buildAlertUpdateVariables(input AlertUpdateInput) map[string]any {
	return map[string]any{
		"uuids":  input.UUIDs,
		"status": input.Status,
	}
}
