// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

// Code generated by tools/generate. DO NOT EDIT.

package jamfprotect

import (
	"context"
	"fmt"
)

// ── Query/Mutation constants ──────────────────────────────────────────────────

const analyticFields = `
fragment AnalyticFields on Analytic {
	uuid
	hash
	name
	label
	inputType
	filter
	description
	longDescription
	created
	updated
	startup
	actions
	analyticActions {
		name
		parameters
	}
	tenantActions {
		name
		parameters
	}
	tags
	level
	severity
	tenantSeverity
	snapshotFiles
	context {
		exprs
		name
		type
	}
	categories
	jamf
	remediation
	matchReason
}
`

const createAnalyticMutation = `
mutation createAnalytic($actions: [String], $analyticActions: [AnalyticActionsInput]!, $categories: [String]!, $context: [AnalyticContextInput]!, $description: String!, $longDescription: String, $filter: String!, $startup: Boolean, $inputType: String!, $level: Int!, $name: String!, $label: String, $snapshotFiles: [String]!, $tags: [String]!, $severity: SEVERITY, $remediation: String, $matchReason: String) {
	createAnalytic(
		input: {actions: $actions, analyticActions: $analyticActions, categories: $categories, context: $context, description: $description, longDescription: $longDescription, filter: $filter, startup: $startup, inputType: $inputType, level: $level, name: $name, label: $label, snapshotFiles: $snapshotFiles, tags: $tags, severity: $severity, remediation: $remediation, matchReason: $matchReason}
	) {
		...AnalyticFields
	}
}
` + analyticFields

const getAnalyticQuery = `
query getAnalytic($uuid: ID!) {
	getAnalytic(uuid: $uuid) {
		...AnalyticFields
	}
}
` + analyticFields

const updateAnalyticMutation = `
mutation updateAnalytic($uuid: ID!, $actions: [String], $analyticActions: [AnalyticActionsInput]!, $categories: [String]!, $context: [AnalyticContextInput]!, $description: String!, $longDescription: String, $filter: String!, $startup: Boolean, $inputType: String!, $level: Int!, $name: String!, $label: String, $snapshotFiles: [String]!, $tags: [String]!, $severity: SEVERITY, $remediation: String, $matchReason: String) {
	updateAnalytic(
		uuid: $uuid
		input: {actions: $actions, analyticActions: $analyticActions, categories: $categories, context: $context, description: $description, longDescription: $longDescription, filter: $filter, startup: $startup, inputType: $inputType, level: $level, name: $name, label: $label, snapshotFiles: $snapshotFiles, tags: $tags, severity: $severity, remediation: $remediation, matchReason: $matchReason}
	) {
		...AnalyticFields
	}
}
` + analyticFields

const updateInternalAnalyticMutation = `
mutation updateInternalAnalytic($uuid: ID!, $tenantActions: [AnalyticActionsInput], $tenantSeverity: SEVERITY) {
	updateInternalAnalytic(
		uuid: $uuid
		input: {tenantActions: $tenantActions, tenantSeverity: $tenantSeverity}
	) {
		...AnalyticFields
	}
}
` + analyticFields

const deleteAnalyticMutation = `
mutation deleteAnalytic($uuid: ID!) {
	deleteAnalytic(uuid: $uuid) {
		uuid
	}
}
`

const listAnalyticsQuery = `
query listAnalytics {
	listAnalytics {
		items {
			...AnalyticFields
		}
	}
}
` + analyticFields

// ── Input types ───────────────────────────────────────────────────────────────

// AnalyticInput is the input for analytic operations.
type AnalyticInput struct {
	Actions         []string
	AnalyticActions []AnalyticActionInput
	Categories      []string
	Context         []AnalyticContextInput
	Description     string
	LongDescription string
	Filter          string
	Startup         *bool
	InputType       string
	Level           int64
	Name            string
	Label           string
	SnapshotFiles   []string
	Tags            []string
	Severity        string
	Remediation     string
	MatchReason     string
}

// AnalyticActionInput is a nested input type.
type AnalyticActionInput struct {
	Name       string `json:"name"`
	Parameters string `json:"parameters"`
}

// AnalyticContextInput is a nested input type.
type AnalyticContextInput struct {
	Exprs []string `json:"exprs"`
	Name  string   `json:"name"`
	Type  string   `json:"type"`
}

// InternalAnalyticInput is the input for internalAnalytic operations.
type InternalAnalyticInput struct {
	TenantActions      []AnalyticActionInput
	TenantActionsNull  bool
	TenantSeverity     *string
	TenantSeverityNull bool
}

// ── Response types ────────────────────────────────────────────────────────────

// AnalyticAction contains AnalyticActions data.
type AnalyticAction struct {
	Name       string `json:"name"`
	Parameters string `json:"parameters"`
}

// AnalyticContext contains AnalyticContext data.
type AnalyticContext struct {
	Exprs []string `json:"exprs"`
	Name  string   `json:"name"`
	Type  string   `json:"type"`
}

// Analytic represents a Jamf Protect analytic.
type Analytic struct {
	UUID            string            `json:"uuid"`
	Hash            string            `json:"hash"`
	Name            string            `json:"name"`
	Label           string            `json:"label"`
	InputType       string            `json:"inputType"`
	Filter          string            `json:"filter"`
	Description     string            `json:"description"`
	LongDescription string            `json:"longDescription"`
	Created         string            `json:"created"`
	Updated         string            `json:"updated"`
	Startup         bool              `json:"startup"`
	Actions         []string          `json:"actions"`
	AnalyticActions []AnalyticAction  `json:"analyticActions"`
	TenantActions   []AnalyticAction  `json:"tenantActions"`
	Tags            []string          `json:"tags"`
	Level           int64             `json:"level"`
	Severity        string            `json:"severity"`
	TenantSeverity  string            `json:"tenantSeverity"`
	SnapshotFiles   []string          `json:"snapshotFiles"`
	Context         []AnalyticContext `json:"context"`
	Categories      []string          `json:"categories"`
	Jamf            bool              `json:"jamf"`
	Remediation     string            `json:"remediation"`
	MatchReason     string            `json:"matchReason"`
}

// ── Client methods ────────────────────────────────────────────────────────────

// CreateAnalytic creates a new analytic.
func (c *Client) CreateAnalytic(ctx context.Context, input AnalyticInput) (Analytic, error) {
	vars := buildAnalyticVariables(input)
	var result struct {
		CreateAnalytic Analytic `json:"createAnalytic"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", createAnalyticMutation, vars, &result); err != nil {
		return Analytic{}, fmt.Errorf("CreateAnalytic: %w", err)
	}
	return result.CreateAnalytic, nil
}

// GetAnalytic retrieves a analytic by ID.
func (c *Client) GetAnalytic(ctx context.Context, uuid string) (*Analytic, error) {
	vars := map[string]any{"uuid": uuid}
	var result struct {
		GetAnalytic *Analytic `json:"getAnalytic"`
	}
	if err := c.transport.DoGraphQL(ctx, "/graphql", getAnalyticQuery, vars, &result); err != nil {
		return nil, fmt.Errorf("GetAnalytic(%s): %w", uuid, err)
	}
	return result.GetAnalytic, nil
}

// UpdateAnalytic updates an existing analytic.
func (c *Client) UpdateAnalytic(ctx context.Context, uuid string, input AnalyticInput) (Analytic, error) {
	vars := buildAnalyticVariables(input)
	vars["uuid"] = uuid
	var result struct {
		UpdateAnalytic Analytic `json:"updateAnalytic"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", updateAnalyticMutation, vars, &result); err != nil {
		return Analytic{}, fmt.Errorf("UpdateAnalytic(%s): %w", uuid, err)
	}
	return result.UpdateAnalytic, nil
}

// UpdateInternalAnalytic updates an existing analytic.
func (c *Client) UpdateInternalAnalytic(ctx context.Context, uuid string, input InternalAnalyticInput) (Analytic, error) {
	vars := buildInternalAnalyticVariables(input)
	vars["uuid"] = uuid
	var result struct {
		UpdateInternalAnalytic Analytic `json:"updateInternalAnalytic"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", updateInternalAnalyticMutation, vars, &result); err != nil {
		return Analytic{}, fmt.Errorf("UpdateInternalAnalytic(%s): %w", uuid, err)
	}
	return result.UpdateInternalAnalytic, nil
}

// DeleteAnalytic deletes a analytic by ID.
func (c *Client) DeleteAnalytic(ctx context.Context, uuid string) error {
	vars := map[string]any{"uuid": uuid}
	if err := c.transport.DoGraphQL(ctx, "/app", deleteAnalyticMutation, vars, nil); err != nil {
		return fmt.Errorf("DeleteAnalytic(%s): %w", uuid, err)
	}
	return nil
}

// ListAnalytics retrieves all analytics.
func (c *Client) ListAnalytics(ctx context.Context) ([]Analytic, error) {
	var result struct {
		ListAnalytics struct {
			Items []Analytic `json:"items"`
		} `json:"listAnalytics"`
	}
	if err := c.transport.DoGraphQL(ctx, "/graphql", listAnalyticsQuery, nil, &result); err != nil {
		return nil, fmt.Errorf("ListAnalytics: %w", err)
	}
	analytics := result.ListAnalytics.Items
	return analytics, nil
}

func buildAnalyticVariables(input AnalyticInput) map[string]any {
	vars := map[string]any{
		"actions":         input.Actions,
		"analyticActions": input.AnalyticActions,
		"categories":      input.Categories,
		"context":         input.Context,
		"description":     input.Description,
		"filter":          input.Filter,
		"inputType":       input.InputType,
		"level":           input.Level,
		"name":            input.Name,
		"snapshotFiles":   input.SnapshotFiles,
		"tags":            input.Tags,
		"severity":        input.Severity,
	}
	if input.LongDescription != "" {
		vars["longDescription"] = input.LongDescription
	}
	if input.Startup != nil {
		vars["startup"] = *input.Startup
	}
	if input.Label != "" {
		vars["label"] = input.Label
	}
	if input.Remediation != "" {
		vars["remediation"] = input.Remediation
	}
	if input.MatchReason != "" {
		vars["matchReason"] = input.MatchReason
	}
	return vars
}

func buildInternalAnalyticVariables(input InternalAnalyticInput) map[string]any {
	vars := map[string]any{}
	if input.TenantActionsNull {
		vars["tenantActions"] = nil
	} else if input.TenantActions != nil {
		vars["tenantActions"] = input.TenantActions
	}
	if input.TenantSeverityNull {
		vars["tenantSeverity"] = nil
	} else if input.TenantSeverity != nil {
		vars["tenantSeverity"] = *input.TenantSeverity
	}
	return vars
}
