// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

// Code generated by tools/generate. DO NOT EDIT.

package jamfprotect

import (
	"context"
	"fmt"

	"github.com/Jamf-Concepts/jamfprotect-go-sdk/internal/client"
)

// ── Query/Mutation constants ──────────────────────────────────────────────────

const analyticSetFields = `
fragment AnalyticSetFields on AnalyticSet {
	uuid
	name
	description
	analytics @skip(if: $excludeAnalytics) {
		uuid
		name
		jamf
	}
	plans @include(if: $RBAC_Plan) {
		id
		name
	}
	created
	updated
	managed
	types
}
`

const createAnalyticSetMutation = `
mutation createAnalyticSet($name: String!, $description: String, $analytics: [ID!]!, $types: [ANALYTIC_SET_TYPE!], $RBAC_Plan: Boolean!, $excludeAnalytics: Boolean!) {
	createAnalyticSet(
		input: {name: $name, description: $description, analytics: $analytics, types: $types}
	) {
		...AnalyticSetFields
	}
}
` + analyticSetFields

const getAnalyticSetQuery = `
query getAnalyticSet($uuid: ID!, $RBAC_Plan: Boolean!, $excludeAnalytics: Boolean!) {
	getAnalyticSet(uuid: $uuid) {
		...AnalyticSetFields
	}
}
` + analyticSetFields

const updateAnalyticSetMutation = `
mutation updateAnalyticSet($uuid: ID!, $name: String!, $description: String, $analytics: [ID!]!, $types: [ANALYTIC_SET_TYPE!], $RBAC_Plan: Boolean!, $excludeAnalytics: Boolean!) {
	updateAnalyticSet(
		uuid: $uuid
		input: {name: $name, description: $description, analytics: $analytics, types: $types}
	) {
		...AnalyticSetFields
	}
}
` + analyticSetFields

const deleteAnalyticSetMutation = `
mutation deleteAnalyticSet($uuid: ID!) {
	deleteAnalyticSet(uuid: $uuid) {
		uuid
	}
}
`

const listAnalyticSetsQuery = `
query listAnalyticSets($nextToken: String, $direction: OrderDirection!, $field: AnalyticSetOrderField!, $filter: AnalyticSetFiltersInput, $pageSize: Int, $RBAC_Plan: Boolean!, $excludeAnalytics: Boolean!) {
	listAnalyticSets(
		input: {next: $nextToken, order: {direction: $direction, field: $field}, filter: $filter, pageSize: $pageSize}
	) {
		items {
			...AnalyticSetFields
		}
		pageInfo {
			next
			total
		}
	}
}
` + analyticSetFields

// ── Input types ───────────────────────────────────────────────────────────────

// AnalyticSetInput is the input for analyticSet operations.
type AnalyticSetInput struct {
	Name        string
	Description string
	Analytics   []string
	Types       []string
}

// ── Response types ────────────────────────────────────────────────────────────

// AnalyticSetAnalytic contains Analytic data.
type AnalyticSetAnalytic struct {
	UUID string `json:"uuid"`
	Name string `json:"name"`
	Jamf bool   `json:"jamf"`
}

// AnalyticSetPlan contains Plan data.
type AnalyticSetPlan struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// AnalyticSet represents a Jamf Protect analyticSet.
type AnalyticSet struct {
	UUID        string                `json:"uuid"`
	Name        string                `json:"name"`
	Description string                `json:"description"`
	Analytics   []AnalyticSetAnalytic `json:"analytics"`
	Plans       []AnalyticSetPlan     `json:"plans"`
	Created     string                `json:"created"`
	Updated     string                `json:"updated"`
	Managed     bool                  `json:"managed"`
	Types       []string              `json:"types"`
}

// ── Client methods ────────────────────────────────────────────────────────────

// CreateAnalyticSet creates a new analyticSet.
func (c *Client) CreateAnalyticSet(ctx context.Context, input AnalyticSetInput) (AnalyticSet, error) {
	vars := mergeVars(buildAnalyticSetVariables(input), map[string]any{"excludeAnalytics": false}, rbacPlan)
	var result struct {
		CreateAnalyticSet AnalyticSet `json:"createAnalyticSet"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", createAnalyticSetMutation, vars, &result); err != nil {
		return AnalyticSet{}, fmt.Errorf("CreateAnalyticSet: %w", err)
	}
	return result.CreateAnalyticSet, nil
}

// GetAnalyticSet retrieves a analyticSet by ID.
func (c *Client) GetAnalyticSet(ctx context.Context, uuid string) (*AnalyticSet, error) {
	vars := mergeVars(map[string]any{"uuid": uuid}, map[string]any{"excludeAnalytics": false}, rbacPlan)
	var result struct {
		GetAnalyticSet *AnalyticSet `json:"getAnalyticSet"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", getAnalyticSetQuery, vars, &result); err != nil {
		return nil, fmt.Errorf("GetAnalyticSet(%s): %w", uuid, err)
	}
	return result.GetAnalyticSet, nil
}

// UpdateAnalyticSet updates an existing analyticSet.
func (c *Client) UpdateAnalyticSet(ctx context.Context, uuid string, input AnalyticSetInput) (AnalyticSet, error) {
	vars := mergeVars(buildAnalyticSetVariables(input), map[string]any{"excludeAnalytics": false}, rbacPlan)
	vars["uuid"] = uuid
	var result struct {
		UpdateAnalyticSet AnalyticSet `json:"updateAnalyticSet"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", updateAnalyticSetMutation, vars, &result); err != nil {
		return AnalyticSet{}, fmt.Errorf("UpdateAnalyticSet(%s): %w", uuid, err)
	}
	return result.UpdateAnalyticSet, nil
}

// DeleteAnalyticSet deletes a analyticSet by ID.
func (c *Client) DeleteAnalyticSet(ctx context.Context, uuid string) error {
	vars := map[string]any{"uuid": uuid}
	if err := c.transport.DoGraphQL(ctx, "/app", deleteAnalyticSetMutation, vars, nil); err != nil {
		return fmt.Errorf("DeleteAnalyticSet(%s): %w", uuid, err)
	}
	return nil
}

// ListAnalyticSets retrieves all analyticSets.
func (c *Client) ListAnalyticSets(ctx context.Context) ([]AnalyticSet, error) {
	analyticSets, err := client.ListAll[AnalyticSet](ctx, c.transport, "/app", listAnalyticSetsQuery, mergeVars(map[string]any{
		"direction":        "DESC",
		"excludeAnalytics": false,
		"field":            "created",
		"filter":           map[string]any{},
		"pageSize":         100,
	}, rbacPlan), "listAnalyticSets")
	if err != nil {
		return nil, fmt.Errorf("ListAnalyticSets: %w", err)
	}
	return analyticSets, nil
}

func buildAnalyticSetVariables(input AnalyticSetInput) map[string]any {
	return map[string]any{
		"name":        input.Name,
		"description": input.Description,
		"analytics":   input.Analytics,
		"types":       input.Types,
	}
}
