// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

// Code generated by tools/generate. DO NOT EDIT.

package jamfprotect

import (
	"context"
	"fmt"

	"github.com/Jamf-Concepts/jamfprotect-go-sdk/internal/client"
)

// ── Query/Mutation constants ──────────────────────────────────────────────────

const apiClientFields = `
fragment ApiClientFields on ApiClient {
	clientId
	created
	name
	assignedRoles {
		id
		name
	}
	password
}
`

const getApiClientQuery = `
query getApiClient($clientId: ID!) {
	getApiClient(clientId: $clientId) {
		...ApiClientFields
	}
}
` + apiClientFields

const createApiClientMutation = `
mutation createApiClient($name: String, $roleIds: [ID]) {
	createApiClient(
		input: {name: $name, roleIds: $roleIds}
	) {
		...ApiClientFields
	}
}
` + apiClientFields

const updateApiClientMutation = `
mutation updateApiClient($clientId: ID!, $name: String, $roleIds: [ID]) {
	updateApiClient(
		clientId: $clientId
		input: {name: $name, roleIds: $roleIds}
	) {
		...ApiClientFields
	}
}
` + apiClientFields

const deleteApiClientMutation = `
mutation deleteApiClient($clientId: ID!) {
	deleteApiClient(clientId: $clientId) {
		...ApiClientFields
	}
}
` + apiClientFields

const listApiClientsQuery = `
query listApiClients($nextToken: String, $direction: OrderDirection!, $field: ApiClientOrderField!, $pageSize: Int) {
	listApiClients(
		input: {next: $nextToken, order: {direction: $direction, field: $field}, pageSize: $pageSize}
	) {
		items {
			...ApiClientFields
		}
		pageInfo {
			next
			total
		}
	}
}
` + apiClientFields

// ── Input types ───────────────────────────────────────────────────────────────

// ApiClientInput is the input for apiClient operations.
type ApiClientInput struct {
	Name    string
	RoleIDs []string
}

// ── Response types ────────────────────────────────────────────────────────────

// ApiClientRole contains Role data.
type ApiClientRole struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// ApiClient represents a Jamf Protect apiClient.
type ApiClient struct {
	ClientID      string          `json:"clientId"`
	Created       string          `json:"created"`
	Name          string          `json:"name"`
	AssignedRoles []ApiClientRole `json:"assignedRoles"`
	Password      string          `json:"password"`
}

// ── Client methods ────────────────────────────────────────────────────────────

// GetApiClient retrieves a apiClient by ID.
func (c *Client) GetApiClient(ctx context.Context, clientId string) (*ApiClient, error) {
	vars := map[string]any{"clientId": clientId}
	var result struct {
		GetApiClient *ApiClient `json:"getApiClient"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", getApiClientQuery, vars, &result); err != nil {
		return nil, fmt.Errorf("GetApiClient(%s): %w", clientId, err)
	}
	return result.GetApiClient, nil
}

// CreateApiClient creates a new apiClient.
func (c *Client) CreateApiClient(ctx context.Context, input ApiClientInput) (ApiClient, error) {
	vars := buildApiClientVariables(input)
	var result struct {
		CreateApiClient ApiClient `json:"createApiClient"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", createApiClientMutation, vars, &result); err != nil {
		return ApiClient{}, fmt.Errorf("CreateApiClient: %w", err)
	}
	return result.CreateApiClient, nil
}

// UpdateApiClient updates an existing apiClient.
func (c *Client) UpdateApiClient(ctx context.Context, clientId string, input ApiClientInput) (ApiClient, error) {
	vars := buildApiClientVariables(input)
	vars["clientId"] = clientId
	var result struct {
		UpdateApiClient ApiClient `json:"updateApiClient"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", updateApiClientMutation, vars, &result); err != nil {
		return ApiClient{}, fmt.Errorf("UpdateApiClient(%s): %w", clientId, err)
	}
	return result.UpdateApiClient, nil
}

// DeleteApiClient deletes a apiClient by ID.
func (c *Client) DeleteApiClient(ctx context.Context, clientId string) error {
	vars := map[string]any{"clientId": clientId}
	if err := c.transport.DoGraphQL(ctx, "/app", deleteApiClientMutation, vars, nil); err != nil {
		return fmt.Errorf("DeleteApiClient(%s): %w", clientId, err)
	}
	return nil
}

// ListApiClients retrieves all apiClients.
func (c *Client) ListApiClients(ctx context.Context) ([]ApiClient, error) {
	apiClients, err := client.ListAll[ApiClient](ctx, c.transport, "/app", listApiClientsQuery, map[string]any{
		"direction": "DESC",
		"field":     "created",
		"pageSize":  100,
	}, "listApiClients")
	if err != nil {
		return nil, fmt.Errorf("ListApiClients: %w", err)
	}
	return apiClients, nil
}

func buildApiClientVariables(input ApiClientInput) map[string]any {
	return map[string]any{
		"name":    input.Name,
		"roleIds": input.RoleIDs,
	}
}
