// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

// Code generated by tools/generate. DO NOT EDIT.

package jamfprotect

import (
	"context"
	"fmt"
)

// ── Query/Mutation constants ──────────────────────────────────────────────────

const auditLogFields = `
fragment AuditLogFields on AuditLog {
	resourceId
	date
	args
	error
	ips
	op
	user
}
`

const listAuditLogsByDateQuery = `
query listAuditLogsByDate(
	$next: String, $pageSize: Int, $order: AuditLogsOrderInput, $condition: AuditLogsDateConditionInput
) {
	listAuditLogsByDate(
		input: {next: $next, pageSize: $pageSize, order: $order, condition: $condition}
	) {
		items {
			...AuditLogFields
		}
		pageInfo {
			next
			total
		}
	}
}
` + auditLogFields

// ── Input types ───────────────────────────────────────────────────────────────

// ── Response types ────────────────────────────────────────────────────────────

// AuditLog represents a Jamf Protect auditLog.
type AuditLog struct {
	ResourceID string  `json:"resourceId"`
	Date       string  `json:"date"`
	Args       string  `json:"args"`
	Error      *string `json:"error"`
	IPs        string  `json:"ips"`
	Op         string  `json:"op"`
	User       string  `json:"user"`
}

// ── Client methods ────────────────────────────────────────────────────────────

// ListAuditLogsByDate retrieves auditLogs within a date range.
func (c *Client) ListAuditLogsByDate(ctx context.Context, dateRange *AuditLogDateRange) ([]AuditLog, error) {
	vars := map[string]any{
		"pageSize":  500,
		"order":     map[string]any{"direction": "DESC"},
		"condition": auditLogCondition(dateRange),
	}
	auditLogs, err := c.fetchAllAuditLogs(ctx, listAuditLogsByDateQuery, vars, "listAuditLogsByDate")
	if err != nil {
		return nil, fmt.Errorf("ListAuditLogsByDate: %w", err)
	}
	return auditLogs, nil
}
