// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

// Code generated by tools/generate. DO NOT EDIT.

package jamfprotect

import (
	"context"
	"fmt"
)

// ── Query/Mutation constants ──────────────────────────────────────────────────

const getBetaAcceptanceStatusQuery = `
query getAppInitializationData {
	getAppInitializationData {
		betaAcceptanceStatus {
			betaName
		acceptedTimestamp
		acceptedUser
		}
	}
}
`

const updateBetaAcceptanceStatusMutation = `
mutation updateBetaAcceptanceStatus($betaName: BetaName!) {
	updateBetaAcceptanceStatus(input: {betaName: $betaName}) {
		betaAcceptanceStatus {
			betaName
		acceptedTimestamp
		acceptedUser
		}
	}
}
`

// BetaName identifies a beta program in Jamf Protect.
type BetaName string

const (
	// BetaNameNGTP is the NGTP_BETA value.
	BetaNameNGTP BetaName = "NGTP_BETA"
)

// ── Input types ───────────────────────────────────────────────────────────────

// ── Response types ────────────────────────────────────────────────────────────

// BetaAcceptanceStatus represents a Jamf Protect betaAcceptanceStatus.
type BetaAcceptanceStatus struct {
	BetaName          string `json:"betaName"`
	AcceptedTimestamp string `json:"acceptedTimestamp"`
	AcceptedUser      string `json:"acceptedUser"`
}

// ── Client methods ────────────────────────────────────────────────────────────

// GetBetaAcceptanceStatus retrieves the betaAcceptanceStatus.
func (c *Client) GetBetaAcceptanceStatus(ctx context.Context) ([]BetaAcceptanceStatus, error) {
	var result struct {
		GetAppInitializationData struct {
			BetaAcceptanceStatus []BetaAcceptanceStatus `json:"betaAcceptanceStatus"`
		} `json:"getAppInitializationData"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", getBetaAcceptanceStatusQuery, nil, &result); err != nil {
		return nil, fmt.Errorf("GetBetaAcceptanceStatus: %w", err)
	}
	return result.GetAppInitializationData.BetaAcceptanceStatus, nil
}

// UpdateBetaAcceptanceStatus bulk-updates betaAcceptanceStatuss.
func (c *Client) UpdateBetaAcceptanceStatus(ctx context.Context, betaName BetaName) ([]BetaAcceptanceStatus, error) {
	vars := map[string]any{"betaName": betaName}
	var result struct {
		UpdateBetaAcceptanceStatus struct {
			BetaAcceptanceStatus []BetaAcceptanceStatus `json:"betaAcceptanceStatus"`
		} `json:"updateBetaAcceptanceStatus"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", updateBetaAcceptanceStatusMutation, vars, &result); err != nil {
		return nil, fmt.Errorf("UpdateBetaAcceptanceStatus: %w", err)
	}
	return result.UpdateBetaAcceptanceStatus.BetaAcceptanceStatus, nil
}
