// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

// Code generated by tools/generate. DO NOT EDIT.

package jamfprotect

import (
	"context"
	"fmt"
)

// ── Query/Mutation constants ──────────────────────────────────────────────────

const getConfigFreezeQuery = `
query getAppInitializationData {
	getAppInitializationData {
		configFreeze
	}
}
`

const updateOrganizationConfigFreezeMutation = `
mutation updateOrganizationConfigFreeze($configFreeze: Boolean!) {
	updateOrganizationConfigFreeze(input: {configFreeze: $configFreeze}) {
		configFreeze
	}
}
`

// ── Input types ───────────────────────────────────────────────────────────────

// ── Response types ────────────────────────────────────────────────────────────

// ChangeManagementConfig represents a Jamf Protect changeManagementConfig.
type ChangeManagementConfig struct {
	ConfigFreeze bool `json:"configFreeze"`
}

// ── Client methods ────────────────────────────────────────────────────────────

// GetConfigFreeze retrieves the changeManagementConfig.
func (c *Client) GetConfigFreeze(ctx context.Context) (ChangeManagementConfig, error) {
	var result struct {
		GetConfigFreeze ChangeManagementConfig `json:"getAppInitializationData"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", getConfigFreezeQuery, nil, &result); err != nil {
		return ChangeManagementConfig{}, fmt.Errorf("GetConfigFreeze: %w", err)
	}
	return result.GetConfigFreeze, nil
}

// UpdateOrganizationConfigFreeze updates the changeManagementConfig.
func (c *Client) UpdateOrganizationConfigFreeze(ctx context.Context, configFreeze bool) (ChangeManagementConfig, error) {
	vars := map[string]any{"configFreeze": configFreeze}
	var result struct {
		UpdateOrganizationConfigFreeze ChangeManagementConfig `json:"updateOrganizationConfigFreeze"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", updateOrganizationConfigFreezeMutation, vars, &result); err != nil {
		return ChangeManagementConfig{}, fmt.Errorf("UpdateOrganizationConfigFreeze: %w", err)
	}
	return result.UpdateOrganizationConfigFreeze, nil
}
