// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

// Code generated by tools/generate. DO NOT EDIT.

package jamfprotect

import (
	"context"
	"fmt"

	"github.com/Jamf-Concepts/jamfprotect-go-sdk/internal/client"
)

// ── Query/Mutation constants ──────────────────────────────────────────────────

const computerFields = `
fragment ComputerFields on Computer {
	uuid
	serial
	hostName
	modelName
	osMajor
	osMinor
	osPatch
	arch @skip(if: $isList)
	certid @skip(if: $isList)
	memorySize @skip(if: $isList)
	osString
	kernelVersion @skip(if: $isList)
	installType @skip(if: $isList)
	label
	created
	updated
	version
	checkin
	configHash
	tags
	signaturesVersion @include(if: $RBAC_ThreatPreventionVersion)
	plan @include(if: $RBAC_Plan) {
		id
		name
		hash
	}
	insightsStatsFail @include(if: $RBAC_Insight)
	insightsStatsPass @include(if: $RBAC_Insight)
	insightsStatsUnknown @include(if: $RBAC_Insight)
	insightsUpdated @include(if: $RBAC_Insight)
	provisioningUDID
	connectionStatus
	lastConnection
	lastConnectionIp
	lastDisconnection
	lastDisconnectionReason
	webProtectionActive
	fullDiskAccess
	pendingPlan
}
`

const listComputersQuery = `
query listComputers($nextToken: String, $direction: OrderDirection!, $field: [ComputerOrderField!], $filter: ComputerFiltersInput, $pageSize: Int, $RBAC_Insight: Boolean!, $RBAC_Plan: Boolean!, $RBAC_ThreatPreventionVersion: Boolean!, $isList: Boolean!) {
	listComputers(
		input: {next: $nextToken, order: {direction: $direction, field: $field}, filter: $filter, pageSize: $pageSize}
	) {
		items {
			...ComputerFields
		}
		pageInfo {
			next
			total
		}
	}
}
` + computerFields

const getComputerQuery = `
query getComputer($uuid: ID!, $RBAC_Insight: Boolean!, $RBAC_Plan: Boolean!, $RBAC_ThreatPreventionVersion: Boolean!, $isList: Boolean!) {
	getComputer(uuid: $uuid) {
		...ComputerFields
	}
}
` + computerFields

const deleteComputerMutation = `
mutation deleteComputer($uuid: ID!) {
	deleteComputer(uuid: $uuid) {
		uuid
	}
}
`

const setComputerPlanMutation = `
mutation setComputerPlan($uuid: ID!, $plan: ID!, $RBAC_Insight: Boolean!, $RBAC_Plan: Boolean!, $RBAC_ThreatPreventionVersion: Boolean!, $isList: Boolean!) {
	setComputerPlan(uuid: $uuid, input: {plan: $plan}) {
		...ComputerFields
	}
}
` + computerFields

const updateComputerMutation = `
mutation updateComputer($uuid: ID!, $label: String, $tags: [String], $RBAC_Insight: Boolean!, $RBAC_Plan: Boolean!, $RBAC_ThreatPreventionVersion: Boolean!, $isList: Boolean!) {
	updateComputer(
		uuid: $uuid
		input: {label: $label, tags: $tags}
	) {
		...ComputerFields
	}
}
` + computerFields

// ── Input types ───────────────────────────────────────────────────────────────

// ComputerUpdateInput is the input for computerUpdate operations.
type ComputerUpdateInput struct {
	Label *string
	Tags  []string
}

// ── Response types ────────────────────────────────────────────────────────────

// ComputerPlan contains Plan data.
type ComputerPlan struct {
	ID   *string `json:"id"`
	Name *string `json:"name"`
	Hash *string `json:"hash"`
}

// Computer represents a Jamf Protect computer.
type Computer struct {
	UUID                    *string       `json:"uuid"`
	Serial                  *string       `json:"serial"`
	HostName                *string       `json:"hostName"`
	ModelName               *string       `json:"modelName"`
	OSMajor                 *int64        `json:"osMajor"`
	OSMinor                 *int64        `json:"osMinor"`
	OSPatch                 *int64        `json:"osPatch"`
	Arch                    *string       `json:"arch"`
	CertID                  *string       `json:"certid"`
	MemorySize              *float64      `json:"memorySize"`
	OSString                *string       `json:"osString"`
	KernelVersion           *string       `json:"kernelVersion"`
	InstallType             *string       `json:"installType"`
	Label                   *string       `json:"label"`
	Created                 *string       `json:"created"`
	Updated                 *string       `json:"updated"`
	Version                 *string       `json:"version"`
	Checkin                 *string       `json:"checkin"`
	ConfigHash              *string       `json:"configHash"`
	Tags                    *[]string     `json:"tags"`
	SignaturesVersion       *int64        `json:"signaturesVersion"`
	Plan                    *ComputerPlan `json:"plan"`
	InsightsStatsFail       *int64        `json:"insightsStatsFail"`
	InsightsStatsPass       *int64        `json:"insightsStatsPass"`
	InsightsStatsUnknown    *int64        `json:"insightsStatsUnknown"`
	InsightsUpdated         *string       `json:"insightsUpdated"`
	ProvisioningUDID        *string       `json:"provisioningUDID"`
	ConnectionStatus        *string       `json:"connectionStatus"`
	LastConnection          *string       `json:"lastConnection"`
	LastConnectionIP        *string       `json:"lastConnectionIp"`
	LastDisconnection       *string       `json:"lastDisconnection"`
	LastDisconnectionReason *string       `json:"lastDisconnectionReason"`
	WebProtectionActive     *bool         `json:"webProtectionActive"`
	FullDiskAccess          *string       `json:"fullDiskAccess"`
	PendingPlan             *int64        `json:"pendingPlan"`
}

// ── Client methods ────────────────────────────────────────────────────────────

// ListComputers retrieves all computers.
func (c *Client) ListComputers(ctx context.Context) ([]Computer, error) {
	computers, err := client.ListAll[Computer](ctx, c.transport, "/app", listComputersQuery, mergeVars(map[string]any{
		"direction": "ASC",
		"field":     []any{"hostName"},
		"filter":    nil,
		"isList":    true,
		"pageSize":  100,
	}, rbacComputer), "listComputers")
	if err != nil {
		return nil, fmt.Errorf("ListComputers: %w", err)
	}
	return computers, nil
}

// GetComputer retrieves a computer by ID.
func (c *Client) GetComputer(ctx context.Context, uuid string) (*Computer, error) {
	vars := mergeVars(map[string]any{"uuid": uuid}, map[string]any{"isList": false}, rbacComputer)
	var result struct {
		GetComputer *Computer `json:"getComputer"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", getComputerQuery, vars, &result); err != nil {
		return nil, fmt.Errorf("GetComputer(%s): %w", uuid, err)
	}
	return result.GetComputer, nil
}

// DeleteComputer deletes a computer by ID.
func (c *Client) DeleteComputer(ctx context.Context, uuid string) error {
	vars := map[string]any{"uuid": uuid}
	if err := c.transport.DoGraphQL(ctx, "/app", deleteComputerMutation, vars, nil); err != nil {
		return fmt.Errorf("DeleteComputer(%s): %w", uuid, err)
	}
	return nil
}

// SetComputerPlan updates a *Computer.
func (c *Client) SetComputerPlan(ctx context.Context, uuid string, planID string) (*Computer, error) {
	vars := mergeVars(map[string]any{"uuid": uuid, "plan": planID}, map[string]any{"isList": false}, rbacComputer)
	var result struct {
		SetComputerPlan *Computer `json:"setComputerPlan"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", setComputerPlanMutation, vars, &result); err != nil {
		return nil, fmt.Errorf("SetComputerPlan(%s): %w", uuid, err)
	}
	return result.SetComputerPlan, nil
}

// UpdateComputer updates an existing *Computer.
func (c *Client) UpdateComputer(ctx context.Context, uuid string, input ComputerUpdateInput) (*Computer, error) {
	vars := mergeVars(buildComputerUpdateVariables(input), map[string]any{"isList": false}, rbacComputer)
	vars["uuid"] = uuid
	var result struct {
		UpdateComputer *Computer `json:"updateComputer"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", updateComputerMutation, vars, &result); err != nil {
		return nil, fmt.Errorf("UpdateComputer(%s): %w", uuid, err)
	}
	return result.UpdateComputer, nil
}

func buildComputerUpdateVariables(input ComputerUpdateInput) map[string]any {
	vars := map[string]any{}
	if input.Label != nil {
		vars["label"] = *input.Label
	}
	if input.Tags != nil {
		vars["tags"] = input.Tags
	}
	return vars
}
