// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

// Code generated by tools/generate. DO NOT EDIT.

package jamfprotect

import (
	"context"
	"fmt"

	"github.com/Jamf-Concepts/jamfprotect-go-sdk/internal/client"
)

// ── Query/Mutation constants ──────────────────────────────────────────────────

const customPreventListFields = `
fragment CustomPreventListFields on PreventList {
	id
	name
	description
	type
	tags
	list
	count
	created
}
`

const getCustomPreventListQuery = `
query getPreventList($id: ID!) {
	getPreventList(id: $id) {
		...CustomPreventListFields
	}
}
` + customPreventListFields

const createCustomPreventListMutation = `
mutation createPreventList($description: String, $list: [String]!, $name: String!, $tags: [String]!, $type: PREVENT_LIST_TYPE!) {
	createPreventList(
		input: {description: $description, list: $list, name: $name, tags: $tags, type: $type}
	) {
		...CustomPreventListFields
	}
}
` + customPreventListFields

const updateCustomPreventListMutation = `
mutation updatePreventList($id: ID!, $description: String, $list: [String]!, $name: String!, $tags: [String]!, $type: PREVENT_LIST_TYPE!) {
	updatePreventList(
		id: $id
		input: {description: $description, list: $list, name: $name, tags: $tags, type: $type}
	) {
		...CustomPreventListFields
	}
}
` + customPreventListFields

const deleteCustomPreventListMutation = `
mutation deletePreventList($id: ID!) {
	deletePreventList(id: $id) {
		id
	}
}
`

const listCustomPreventListsQuery = `
query listPreventLists($nextToken: String, $direction: OrderDirection!, $field: PreventListOrderField!, $pageSize: Int, $filter: PreventListFilterInput) {
	listPreventLists(
		input: {next: $nextToken, order: {direction: $direction, field: $field}, pageSize: $pageSize, filter: $filter}
	) {
		items {
			...CustomPreventListFields
		}
		pageInfo {
			next
			total
		}
	}
}
` + customPreventListFields

// ── Input types ───────────────────────────────────────────────────────────────

// CustomPreventListInput is the input for customPreventList operations.
type CustomPreventListInput struct {
	Description string
	List        []string
	Name        string
	Tags        []string
	Type        string
}

// ── Response types ────────────────────────────────────────────────────────────

// CustomPreventList represents a Jamf Protect customPreventList.
type CustomPreventList struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Type        string   `json:"type"`
	Tags        []string `json:"tags"`
	List        []string `json:"list"`
	Count       int64    `json:"count"`
	Created     string   `json:"created"`
}

// ── Client methods ────────────────────────────────────────────────────────────

// GetCustomPreventList retrieves a customPreventList by ID.
func (c *Client) GetCustomPreventList(ctx context.Context, id string) (*CustomPreventList, error) {
	vars := map[string]any{"id": id}
	var result struct {
		GetCustomPreventList *CustomPreventList `json:"getPreventList"`
	}
	if err := c.transport.DoGraphQL(ctx, "/graphql", getCustomPreventListQuery, vars, &result); err != nil {
		return nil, fmt.Errorf("GetCustomPreventList(%s): %w", id, err)
	}
	return result.GetCustomPreventList, nil
}

// CreateCustomPreventList creates a new customPreventList.
func (c *Client) CreateCustomPreventList(ctx context.Context, input CustomPreventListInput) (CustomPreventList, error) {
	vars := buildCustomPreventListVariables(input)
	var result struct {
		CreateCustomPreventList CustomPreventList `json:"createPreventList"`
	}
	if err := c.transport.DoGraphQL(ctx, "/graphql", createCustomPreventListMutation, vars, &result); err != nil {
		return CustomPreventList{}, fmt.Errorf("CreateCustomPreventList: %w", err)
	}
	return result.CreateCustomPreventList, nil
}

// UpdateCustomPreventList updates an existing customPreventList.
func (c *Client) UpdateCustomPreventList(ctx context.Context, id string, input CustomPreventListInput) (CustomPreventList, error) {
	vars := buildCustomPreventListVariables(input)
	vars["id"] = id
	var result struct {
		UpdateCustomPreventList CustomPreventList `json:"updatePreventList"`
	}
	if err := c.transport.DoGraphQL(ctx, "/graphql", updateCustomPreventListMutation, vars, &result); err != nil {
		return CustomPreventList{}, fmt.Errorf("UpdateCustomPreventList(%s): %w", id, err)
	}
	return result.UpdateCustomPreventList, nil
}

// DeleteCustomPreventList deletes a customPreventList by ID.
func (c *Client) DeleteCustomPreventList(ctx context.Context, id string) error {
	vars := map[string]any{"id": id}
	if err := c.transport.DoGraphQL(ctx, "/graphql", deleteCustomPreventListMutation, vars, nil); err != nil {
		return fmt.Errorf("DeleteCustomPreventList(%s): %w", id, err)
	}
	return nil
}

// ListCustomPreventLists retrieves all customPreventLists.
func (c *Client) ListCustomPreventLists(ctx context.Context) ([]CustomPreventList, error) {
	customPreventLists, err := client.ListAll[CustomPreventList](ctx, c.transport, "/graphql", listCustomPreventListsQuery, map[string]any{
		"direction": "DESC",
		"field":     "created",
		"filter":    map[string]any{},
		"pageSize":  100,
	}, "listPreventLists")
	if err != nil {
		return nil, fmt.Errorf("ListCustomPreventLists: %w", err)
	}
	return customPreventLists, nil
}

func buildCustomPreventListVariables(input CustomPreventListInput) map[string]any {
	return map[string]any{
		"description": input.Description,
		"list":        input.List,
		"name":        input.Name,
		"tags":        input.Tags,
		"type":        input.Type,
	}
}
