// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

// Code generated by tools/generate. DO NOT EDIT.

package jamfprotect

import (
	"context"
	"fmt"
)

// ── Query/Mutation constants ──────────────────────────────────────────────────

const getCountQuery = `
query getCount($input: CountQueryInput) {
	getCount(input: $input) {
		computers
		alerts
		alertsComputers
		insightsComputers
	}
}
`

const getComputerCountQuery = `
query getComputerCount {
	getComputerCount {
		computers
	}
}
`

const listRiskiestComputersQuery = `
query listRiskiestComputers($createdInterval: String, $limit: Int) {
	listRiskiestComputers(input: {createdInterval: $createdInterval, limit: $limit}) {
		items {
			computer {
				uuid
				hostName
				serial
			}
			alertCounts {
				severity
				count
			}
		}
	}
}
`

// ── Input types ───────────────────────────────────────────────────────────────

// ── Response types ────────────────────────────────────────────────────────────

// RiskyComputer contains RiskyComputer data.
type RiskyComputer struct {
	Computer    *RiskyComputerRef     `json:"computer"`
	AlertCounts []RiskyComputerAlerts `json:"alertCounts"`
}

// RiskyComputerRef contains Computer data.
type RiskyComputerRef struct {
	UUID     string `json:"uuid"`
	HostName string `json:"hostName"`
	Serial   string `json:"serial"`
}

// RiskyComputerAlerts contains AlertCount data.
type RiskyComputerAlerts struct {
	Severity string `json:"severity"`
	Count    int64  `json:"count"`
}

// CountResponse represents a Jamf Protect countResponse.
type CountResponse struct {
	Computers         *int64 `json:"computers"`
	Alerts            *int64 `json:"alerts"`
	AlertsComputers   *int64 `json:"alertsComputers"`
	InsightsComputers *int64 `json:"insightsComputers"`
}

// ── Client methods ────────────────────────────────────────────────────────────

// GetCount retrieves the countResponse.
func (c *Client) GetCount(ctx context.Context) (CountResponse, error) {
	vars := map[string]any{"input": map[string]any{"alerts": map[string]any{"or": []any{}}, "alertsComputers": map[string]any{"or": []any{}}, "computers": map[string]any{"or": []any{}}, "insightsComputers": map[string]any{"or": []any{}}}}
	var result struct {
		GetCount CountResponse `json:"getCount"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", getCountQuery, vars, &result); err != nil {
		return CountResponse{}, fmt.Errorf("GetCount: %w", err)
	}
	return result.GetCount, nil
}

// GetComputerCount retrieves the int64.
func (c *Client) GetComputerCount(ctx context.Context) (int64, error) {
	var result struct {
		GetComputerCount struct {
			Computers int64 `json:"computers"`
		} `json:"getComputerCount"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", getComputerCountQuery, nil, &result); err != nil {
		return 0, fmt.Errorf("GetComputerCount: %w", err)
	}
	return result.GetComputerCount.Computers, nil
}

// ListRiskiestComputers retrieves riskyComputers filtered by the given args.
func (c *Client) ListRiskiestComputers(ctx context.Context, limit int, createdInterval string) ([]RiskyComputer, error) {
	vars := map[string]any{}
	if limit > 0 {
		vars["limit"] = limit
	}
	if createdInterval != "" {
		vars["createdInterval"] = createdInterval
	}
	var result struct {
		ListRiskiestComputers struct {
			Items []RiskyComputer `json:"items"`
		} `json:"listRiskiestComputers"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", listRiskiestComputersQuery, vars, &result); err != nil {
		return nil, fmt.Errorf("ListRiskiestComputers: %w", err)
	}
	return result.ListRiskiestComputers.Items, nil
}
