// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

// Code generated by tools/generate. DO NOT EDIT.

package jamfprotect

import (
	"context"
	"fmt"
)

// ── Query/Mutation constants ──────────────────────────────────────────────────

const dataRetentionSettingsFields = `
fragment DataRetentionSettingsFields on Retention {
	database {
		log {
			recordCount
			numberOfDays
		}
		alert {
			recordCount
			numberOfDays
		}
	}
	cold {
		alert {
			numberOfDays
		}
	}
	updated
}
`

const getDataRetentionQuery = `
query getOrganization {
	getOrganization {
		retention {
			...DataRetentionSettingsFields
		}
	}
}
` + dataRetentionSettingsFields

const updateDataRetentionMutation = `
mutation updateOrganizationRetention($databaseLogDays: Int!, $databaseAlertDays: Int!, $coldAlertDays: Int!) {
	updateOrganizationRetention(input: {retention: {database: {log: {numberOfDays: $databaseLogDays}, alert: {numberOfDays: $databaseAlertDays}}, cold: {alert: {numberOfDays: $coldAlertDays}}}}) {
		retention {
			...DataRetentionSettingsFields
		}
	}
}
` + dataRetentionSettingsFields

// ── Input types ───────────────────────────────────────────────────────────────

// DataRetentionInput is the input for dataRetention operations.
type DataRetentionInput struct {
	DatabaseLogDays   int64
	DatabaseAlertDays int64
	ColdAlertDays     int64
}

// ── Response types ────────────────────────────────────────────────────────────

// DataRetentionDatabase contains DbStorageRetention data.
type DataRetentionDatabase struct {
	Log   *DataRetentionDays `json:"log"`
	Alert *DataRetentionDays `json:"alert"`
}

// DataRetentionCold contains ColdStorageRetention data.
type DataRetentionCold struct {
	Alert *DataRetentionColdDays `json:"alert"`
}

// DataRetentionDays contains RecordCount data.
type DataRetentionDays struct {
	RecordCount  int64 `json:"recordCount"`
	NumberOfDays int64 `json:"numberOfDays"`
}

// DataRetentionColdDays contains ColdStorageSettings data.
type DataRetentionColdDays struct {
	NumberOfDays int64 `json:"numberOfDays"`
}

// DataRetentionSettings represents a Jamf Protect dataRetentionSettings.
type DataRetentionSettings struct {
	Database *DataRetentionDatabase `json:"database"`
	Cold     *DataRetentionCold     `json:"cold"`
	Updated  string                 `json:"updated"`
}

// ── Client methods ────────────────────────────────────────────────────────────

// GetDataRetention retrieves the dataRetentionSettings.
func (c *Client) GetDataRetention(ctx context.Context) (DataRetentionSettings, error) {
	var result struct {
		GetOrganization struct {
			Retention DataRetentionSettings `json:"retention"`
		} `json:"getOrganization"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", getDataRetentionQuery, nil, &result); err != nil {
		return DataRetentionSettings{}, fmt.Errorf("GetDataRetention: %w", err)
	}
	return result.GetOrganization.Retention, nil
}

// UpdateDataRetention updates the dataRetentionSettings.
func (c *Client) UpdateDataRetention(ctx context.Context, input DataRetentionInput) (DataRetentionSettings, error) {
	vars := map[string]any{"databaseLogDays": input.DatabaseLogDays, "databaseAlertDays": input.DatabaseAlertDays, "coldAlertDays": input.ColdAlertDays}
	var result struct {
		UpdateOrganizationRetention struct {
			Retention DataRetentionSettings `json:"retention"`
		} `json:"updateOrganizationRetention"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", updateDataRetentionMutation, vars, &result); err != nil {
		return DataRetentionSettings{}, fmt.Errorf("UpdateDataRetention: %w", err)
	}
	return result.UpdateOrganizationRetention.Retention, nil
}
