// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

// Code generated by tools/generate. DO NOT EDIT.

package jamfprotect

import (
	"context"
	"fmt"
)

// ── Query/Mutation constants ──────────────────────────────────────────────────

const dataForwardingResultFields = `
fragment DataForwardingResultFields on Organization {
	uuid
	forward {
		s3 {
			bucket
			enabled
			encrypted
			prefix
			role
			cloudformation
		}
		sentinel {
			enabled
			customerId
			sharedKey
			logType
			domain
		}
		sentinelV2 {
			enabled
			azureTenantId
			azureClientId
			secretExists
			endpoint
			alerts {
				enabled
				dcrImmutableId
				streamName
			}
			ulogs {
				enabled
				dcrImmutableId
				streamName
			}
			telemetries {
				enabled
				dcrImmutableId
				streamName
			}
			telemetriesV2 {
				enabled
				dcrImmutableId
				streamName
			}
		}
	}
}
`

const getDataForwardingQuery = `
query getOrganization {
	getOrganization {
		...DataForwardingResultFields
	}
}
` + dataForwardingResultFields

const updateDataForwardingMutation = `
mutation updateOrganizationForward($s3: OrganizationS3ForwardInput!, $sentinel: OrganizationSentinelForwardInput!, $sentinelV2: OrganizationSentinelV2ForwardInput!) {
	updateOrganizationForward(input: {s3: $s3, sentinel: $sentinel, sentinelV2: $sentinelV2}) {
		...DataForwardingResultFields
	}
}
` + dataForwardingResultFields

// ── Input types ───────────────────────────────────────────────────────────────

// ForwardS3Input is a nested input type.
type ForwardS3Input struct {
	Enabled   bool   `json:"enabled"`
	Bucket    string `json:"bucket"`
	Encrypted bool   `json:"encrypted"`
	Prefix    string `json:"prefix"`
	Role      string `json:"role"`
}

// ForwardSentinelInput is a nested input type.
type ForwardSentinelInput struct {
	Enabled    bool   `json:"enabled"`
	CustomerID string `json:"customerId"`
	SharedKey  string `json:"sharedKey"`
	LogType    string `json:"logType"`
	Domain     string `json:"domain"`
}

// DataStreamInput is a nested input type.
type DataStreamInput struct {
	Enabled        bool    `json:"enabled"`
	DcrImmutableID *string `json:"dcrImmutableId,omitempty"`
	StreamName     *string `json:"streamName,omitempty"`
}

// ForwardSentinelV2Input is a nested input type.
type ForwardSentinelV2Input struct {
	Enabled           bool            `json:"enabled"`
	AzureTenantID     string          `json:"azureTenantId"`
	AzureClientID     string          `json:"azureClientId"`
	AzureClientSecret *string         `json:"azureClientSecret,omitempty"`
	Endpoint          string          `json:"endpoint"`
	Alerts            DataStreamInput `json:"alerts"`
	Ulogs             DataStreamInput `json:"ulogs"`
	Telemetries       DataStreamInput `json:"telemetries"`
	TelemetriesV2     DataStreamInput `json:"telemetriesV2"`
}

// DataForwardingInput is the input for dataForwarding operations.
type DataForwardingInput struct {
	S3         ForwardS3Input
	Sentinel   ForwardSentinelInput
	SentinelV2 ForwardSentinelV2Input
}

// ── Response types ────────────────────────────────────────────────────────────

// DataForwardingSettings contains Forward data.
type DataForwardingSettings struct {
	S3         *ForwardS3         `json:"s3"`
	Sentinel   *ForwardSentinel   `json:"sentinel"`
	SentinelV2 *ForwardSentinelV2 `json:"sentinelV2"`
}

// ForwardS3 contains ForwardS3 data.
type ForwardS3 struct {
	Bucket         string `json:"bucket"`
	Enabled        bool   `json:"enabled"`
	Encrypted      bool   `json:"encrypted"`
	Prefix         string `json:"prefix"`
	Role           string `json:"role"`
	CloudFormation string `json:"cloudformation"`
}

// ForwardSentinel contains ForwardSentinel data.
type ForwardSentinel struct {
	Enabled    bool   `json:"enabled"`
	CustomerID string `json:"customerId"`
	SharedKey  string `json:"sharedKey"`
	LogType    string `json:"logType"`
	Domain     string `json:"domain"`
}

// ForwardSentinelV2 contains ForwardSentinelV2 data.
type ForwardSentinelV2 struct {
	Enabled       bool        `json:"enabled"`
	AzureTenantID string      `json:"azureTenantId"`
	AzureClientID string      `json:"azureClientId"`
	SecretExists  bool        `json:"secretExists"`
	Endpoint      string      `json:"endpoint"`
	Alerts        *DataStream `json:"alerts"`
	Ulogs         *DataStream `json:"ulogs"`
	Telemetries   *DataStream `json:"telemetries"`
	TelemetriesV2 *DataStream `json:"telemetriesV2"`
}

// DataStream contains DataStream data.
type DataStream struct {
	Enabled        bool    `json:"enabled"`
	DcrImmutableID *string `json:"dcrImmutableId"`
	StreamName     *string `json:"streamName"`
}

// DataForwardingResult represents a Jamf Protect dataForwardingResult.
type DataForwardingResult struct {
	UUID    string                  `json:"uuid"`
	Forward *DataForwardingSettings `json:"forward"`
}

// ── Client methods ────────────────────────────────────────────────────────────

// GetDataForwarding retrieves the dataForwardingResult.
func (c *Client) GetDataForwarding(ctx context.Context) (DataForwardingResult, error) {
	var result struct {
		GetDataForwarding DataForwardingResult `json:"getOrganization"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", getDataForwardingQuery, nil, &result); err != nil {
		return DataForwardingResult{}, fmt.Errorf("GetDataForwarding: %w", err)
	}
	return result.GetDataForwarding, nil
}

// UpdateDataForwarding updates the dataForwardingResult.
func (c *Client) UpdateDataForwarding(ctx context.Context, input DataForwardingInput) (DataForwardingResult, error) {
	vars := map[string]any{"s3": input.S3, "sentinel": input.Sentinel, "sentinelV2": input.SentinelV2}
	var result struct {
		UpdateOrganizationForward DataForwardingResult `json:"updateOrganizationForward"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", updateDataForwardingMutation, vars, &result); err != nil {
		return DataForwardingResult{}, fmt.Errorf("UpdateDataForwarding: %w", err)
	}
	return result.UpdateOrganizationForward, nil
}
