// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

// Code generated by tools/generate. DO NOT EDIT.

package jamfprotect

import (
	"context"
	"fmt"
)

// ── Query/Mutation constants ──────────────────────────────────────────────────

const organizationDownloadsFields = `
fragment OrganizationDownloadsFields on OrganizationDownload {
	pppc
	rootCA
	csr
	installerUuid
	vanillaPackage {
		version
	}
	websocket_auth
	tamperPreventionProfile
	networkContentFilterProfile
}
`

const getOrganizationDownloadsQuery = `
query getOrganizationDownloads {
	downloads: getOrganizationDownloads {
		...OrganizationDownloadsFields
	}
}
` + organizationDownloadsFields

// ── Input types ───────────────────────────────────────────────────────────────

// ── Response types ────────────────────────────────────────────────────────────

// VanillaPackage contains VanillaPackage data.
type VanillaPackage struct {
	Version string `json:"version"`
}

// OrganizationDownloads represents a Jamf Protect organizationDownloads.
type OrganizationDownloads struct {
	PPPC                        string          `json:"pppc"`
	RootCA                      string          `json:"rootCA"`
	CSR                         string          `json:"csr"`
	InstallerUUID               string          `json:"installerUuid"`
	VanillaPackage              *VanillaPackage `json:"vanillaPackage"`
	WebsocketAuth               string          `json:"websocket_auth"`
	TamperPreventionProfile     string          `json:"tamperPreventionProfile"`
	NetworkContentFilterProfile string          `json:"networkContentFilterProfile"`
}

// ── Client methods ────────────────────────────────────────────────────────────

// GetOrganizationDownloads retrieves the organizationDownloads.
func (c *Client) GetOrganizationDownloads(ctx context.Context) (OrganizationDownloads, error) {
	var result struct {
		GetOrganizationDownloads OrganizationDownloads `json:"downloads"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", getOrganizationDownloadsQuery, nil, &result); err != nil {
		return OrganizationDownloads{}, fmt.Errorf("GetOrganizationDownloads: %w", err)
	}
	return result.GetOrganizationDownloads, nil
}
