// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

// Code generated by tools/generate. DO NOT EDIT.

package jamfprotect

import (
	"context"
	"fmt"

	"github.com/Jamf-Concepts/jamfprotect-go-sdk/internal/client"
)

// ── Query/Mutation constants ──────────────────────────────────────────────────

const exceptionSetFields = `
fragment ExceptionSetFields on ExceptionSet {
	uuid
	name
	description
	exceptions @skip(if: $minimal) {
		type
		value
		appSigningInfo {
			appId
			teamId
		}
		ignoreActivity
		analyticTypes
		analytic {
			name
			uuid
		}
		created
		updated
	}
	esExceptions @skip(if: $minimal) {
		type
		value
		appSigningInfo {
			appId
			teamId
		}
		ignoreActivity
		ignoreListType
		ignoreListSubType
		eventType
		created
		updated
	}
	created
	updated
	managed
}
`

const createExceptionSetMutation = `
mutation createExceptionSet($name: String!, $description: String, $exceptions: [ExceptionInput!]!, $esExceptions: [EsExceptionInput!], $minimal: Boolean!) {
	createExceptionSet(
		input: {name: $name, description: $description, exceptions: $exceptions, esExceptions: $esExceptions}
	) {
		...ExceptionSetFields
	}
}
` + exceptionSetFields

const getExceptionSetQuery = `
query getExceptionSet($uuid: ID!, $minimal: Boolean!) {
	getExceptionSet(uuid: $uuid) {
		...ExceptionSetFields
	}
}
` + exceptionSetFields

const updateExceptionSetMutation = `
mutation updateExceptionSet($uuid: ID!, $name: String!, $description: String, $exceptions: [ExceptionInput!]!, $esExceptions: [EsExceptionInput!], $minimal: Boolean!) {
	updateExceptionSet(
		uuid: $uuid
		input: {name: $name, description: $description, exceptions: $exceptions, esExceptions: $esExceptions}
	) {
		...ExceptionSetFields
	}
}
` + exceptionSetFields

const deleteExceptionSetMutation = `
mutation deleteExceptionSet($uuid: ID!) {
	deleteExceptionSet(uuid: $uuid) {
		uuid
	}
}
`

const listExceptionSetsQuery = `
query listExceptionSets($nextToken: String, $direction: OrderDirection!, $field: ExceptionSetOrderField!, $filter: ExceptionSetFiltersInput, $pageSize: Int) {
	listExceptionSets(
		input: {next: $nextToken, order: {direction: $direction, field: $field}, filter: $filter, pageSize: $pageSize}
	) {
		items {
			uuid
			name
			managed
		}
		pageInfo {
			next
			total
		}
	}
}
`

// ── Input types ───────────────────────────────────────────────────────────────

// ExceptionSetInput is the input for exceptionSet operations.
type ExceptionSetInput struct {
	Name         string
	Description  string
	Exceptions   []ExceptionInput
	EsExceptions []EsExceptionInput
}

// AppSigningInfoInput is a nested input type.
type AppSigningInfoInput struct {
	AppID  string `json:"appId"`
	TeamID string `json:"teamId"`
}

// ExceptionInput is a nested input type.
type ExceptionInput struct {
	Type           string              `json:"type"`
	Value          string              `json:"value"`
	AppSigningInfo AppSigningInfoInput `json:"appSigningInfo"`
	IgnoreActivity string              `json:"ignoreActivity"`
	AnalyticUUID   string              `json:"analyticUuid"`
	AnalyticTypes  []string            `json:"analyticTypes"`
}

// EsExceptionInput is a nested input type.
type EsExceptionInput struct {
	Type              string              `json:"type"`
	Value             string              `json:"value"`
	AppSigningInfo    AppSigningInfoInput `json:"appSigningInfo"`
	IgnoreActivity    string              `json:"ignoreActivity"`
	IgnoreListType    string              `json:"ignoreListType"`
	IgnoreListSubType string              `json:"ignoreListSubType"`
	EventType         string              `json:"eventType"`
}

// ── Response types ────────────────────────────────────────────────────────────

// Exception contains Exception data.
type Exception struct {
	Type           string          `json:"type"`
	Value          string          `json:"value"`
	AppSigningInfo *AppSigningInfo `json:"appSigningInfo"`
	IgnoreActivity string          `json:"ignoreActivity"`
	AnalyticTypes  []string        `json:"analyticTypes"`
	Analytic       *AnalyticRef    `json:"analytic"`
	Created        string          `json:"created"`
	Updated        string          `json:"updated"`
}

// EsException contains EsException data.
type EsException struct {
	Type              string          `json:"type"`
	Value             string          `json:"value"`
	AppSigningInfo    *AppSigningInfo `json:"appSigningInfo"`
	IgnoreActivity    string          `json:"ignoreActivity"`
	IgnoreListType    string          `json:"ignoreListType"`
	IgnoreListSubType string          `json:"ignoreListSubType"`
	EventType         string          `json:"eventType"`
	Created           string          `json:"created"`
	Updated           string          `json:"updated"`
}

// AppSigningInfo contains ExceptionAppSigningInfo data.
type AppSigningInfo struct {
	AppID  string `json:"appId"`
	TeamID string `json:"teamId"`
}

// AnalyticRef contains Analytic data.
type AnalyticRef struct {
	Name string `json:"name"`
	UUID string `json:"uuid"`
}

// ExceptionSetListItem contains ExceptionSet data.
type ExceptionSetListItem struct {
	UUID    string `json:"uuid"`
	Name    string `json:"name"`
	Managed bool   `json:"managed"`
}

// ExceptionSet represents a Jamf Protect exceptionSet.
type ExceptionSet struct {
	UUID         string        `json:"uuid"`
	Name         string        `json:"name"`
	Description  string        `json:"description"`
	Exceptions   []Exception   `json:"exceptions"`
	EsExceptions []EsException `json:"esExceptions"`
	Created      string        `json:"created"`
	Updated      string        `json:"updated"`
	Managed      bool          `json:"managed"`
}

// ── Client methods ────────────────────────────────────────────────────────────

// CreateExceptionSet creates a new exceptionSet.
func (c *Client) CreateExceptionSet(ctx context.Context, input ExceptionSetInput) (ExceptionSet, error) {
	vars := mergeVars(buildExceptionSetVariables(input), map[string]any{"minimal": false})
	var result struct {
		CreateExceptionSet ExceptionSet `json:"createExceptionSet"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", createExceptionSetMutation, vars, &result); err != nil {
		return ExceptionSet{}, fmt.Errorf("CreateExceptionSet: %w", err)
	}
	return result.CreateExceptionSet, nil
}

// GetExceptionSet retrieves a exceptionSet by ID.
func (c *Client) GetExceptionSet(ctx context.Context, uuid string) (*ExceptionSet, error) {
	vars := mergeVars(map[string]any{"uuid": uuid}, map[string]any{"minimal": false})
	var result struct {
		GetExceptionSet *ExceptionSet `json:"getExceptionSet"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", getExceptionSetQuery, vars, &result); err != nil {
		return nil, fmt.Errorf("GetExceptionSet(%s): %w", uuid, err)
	}
	return result.GetExceptionSet, nil
}

// UpdateExceptionSet updates an existing exceptionSet.
func (c *Client) UpdateExceptionSet(ctx context.Context, uuid string, input ExceptionSetInput) (ExceptionSet, error) {
	vars := mergeVars(buildExceptionSetVariables(input), map[string]any{"minimal": false})
	vars["uuid"] = uuid
	var result struct {
		UpdateExceptionSet ExceptionSet `json:"updateExceptionSet"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", updateExceptionSetMutation, vars, &result); err != nil {
		return ExceptionSet{}, fmt.Errorf("UpdateExceptionSet(%s): %w", uuid, err)
	}
	return result.UpdateExceptionSet, nil
}

// DeleteExceptionSet deletes a exceptionSet by ID.
func (c *Client) DeleteExceptionSet(ctx context.Context, uuid string) error {
	vars := map[string]any{"uuid": uuid}
	if err := c.transport.DoGraphQL(ctx, "/app", deleteExceptionSetMutation, vars, nil); err != nil {
		return fmt.Errorf("DeleteExceptionSet(%s): %w", uuid, err)
	}
	return nil
}

// ListExceptionSets retrieves all exceptionSetListItems.
func (c *Client) ListExceptionSets(ctx context.Context) ([]ExceptionSetListItem, error) {
	exceptionSetListItems, err := client.ListAll[ExceptionSetListItem](ctx, c.transport, "/app", listExceptionSetsQuery, map[string]any{
		"direction": "DESC",
		"field":     "created",
		"filter":    map[string]any{},
		"pageSize":  100,
	}, "listExceptionSets")
	if err != nil {
		return nil, fmt.Errorf("ListExceptionSets: %w", err)
	}
	return exceptionSetListItems, nil
}

func buildExceptionSetVariables(input ExceptionSetInput) map[string]any {
	return map[string]any{
		"name":         input.Name,
		"description":  input.Description,
		"exceptions":   input.Exceptions,
		"esExceptions": input.EsExceptions,
	}
}
