// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

// Code generated by tools/generate. DO NOT EDIT.

package jamfprotect

import (
	"context"
	"fmt"

	"github.com/Jamf-Concepts/jamfprotect-go-sdk/internal/client"
)

// ── Query/Mutation constants ──────────────────────────────────────────────────

const connectionFields = `
fragment ConnectionFields on Connection {
	id
	name
	requireKnownUsers
	button
	created
	updated
	strategy
	groupsSupport
	source
}
`

const listConnectionsQuery = `
query listConnections($nextToken: String, $direction: OrderDirection!, $field: ConnectionOrderField!, $pageSize: Int) {
	listConnections(
		input: {next: $nextToken, order: {direction: $direction, field: $field}, pageSize: $pageSize}
	) {
		items {
			...ConnectionFields
		}
		pageInfo {
			next
			total
		}
	}
}
` + connectionFields

// ── Input types ───────────────────────────────────────────────────────────────

// ── Response types ────────────────────────────────────────────────────────────

// Connection represents a Jamf Protect connection.
type Connection struct {
	ID                string `json:"id"`
	Name              string `json:"name"`
	RequireKnownUsers bool   `json:"requireKnownUsers"`
	Button            string `json:"button"`
	Created           string `json:"created"`
	Updated           string `json:"updated"`
	Strategy          string `json:"strategy"`
	GroupsSupport     bool   `json:"groupsSupport"`
	Source            string `json:"source"`
}

// ── Client methods ────────────────────────────────────────────────────────────

// ListConnections retrieves all connections.
func (c *Client) ListConnections(ctx context.Context) ([]Connection, error) {
	connections, err := client.ListAll[Connection](ctx, c.transport, "/app", listConnectionsQuery, map[string]any{
		"direction": "ASC",
		"field":     "name",
		"pageSize":  100,
	}, "listConnections")
	if err != nil {
		return nil, fmt.Errorf("ListConnections: %w", err)
	}
	return connections, nil
}
