// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

// Code generated by tools/generate. DO NOT EDIT.

package jamfprotect

import (
	"context"
	"fmt"

	"github.com/Jamf-Concepts/jamfprotect-go-sdk/internal/client"
)

// ── Query/Mutation constants ──────────────────────────────────────────────────

const insightFields = `
fragment InsightFields on Insight {
	uuid
	label
	description
	section
	totalPass
	totalFail
	totalNone
	tags
	enabled
	cisid {
		osVersion
		id
	}
}
`

const listInsightsQuery = `
query listInsights {
	listInsights {
		...InsightFields
	}
}
` + insightFields

const updateInsightStatusMutation = `
mutation updateInsightStatus($uuid: ID!, $enabled: Boolean!) {
	updateInsightStatus(uuid: $uuid, input: {enabled: $enabled}) {
		...InsightFields
	}
}
` + insightFields

const listInsightComputersQuery = `
query listInsightComputers($uuid: ID!, $nextToken: String, $order: ComputerOrderInput, $filter: ComputerFiltersInput, $pageSize: Int) {
	listInsightComputers(
		uuid: $uuid
		input: {next: $nextToken, order: $order, filter: $filter, pageSize: $pageSize}
	) {
		items {
			uuid
			hostName
			insightsUpdated
			insightsStatsFail
			insightsStatsPass
			insightsStatsUnknown
		}
		pageInfo {
			next
			total
		}
	}
}
`

const getFleetComplianceScoreQuery = `
query getFleetComplianceBaselineScore($date: AWSDate) {
	getFleetComplianceBaselineScore(date: $date) {
		updated
		score
	}
}
`

// ── Input types ───────────────────────────────────────────────────────────────

// InsightInput is the input for insight operations.
type InsightInput struct {
	Enabled bool
}

// ── Response types ────────────────────────────────────────────────────────────

// InsightCisID contains CisId data.
type InsightCisID struct {
	OsVersion string `json:"osVersion"`
	ID        string `json:"id"`
}

// InsightComputer contains Computer data.
type InsightComputer struct {
	UUID                 string `json:"uuid"`
	HostName             string `json:"hostName"`
	InsightsUpdated      string `json:"insightsUpdated"`
	InsightsStatsFail    int64  `json:"insightsStatsFail"`
	InsightsStatsPass    int64  `json:"insightsStatsPass"`
	InsightsStatsUnknown int64  `json:"insightsStatsUnknown"`
}

// ComplianceBaselineScore contains ComplianceBaselineScore data.
type ComplianceBaselineScore struct {
	Updated string  `json:"updated"`
	Score   float64 `json:"score"`
}

// Insight represents a Jamf Protect insight.
type Insight struct {
	UUID        string         `json:"uuid"`
	Label       string         `json:"label"`
	Description string         `json:"description"`
	Section     string         `json:"section"`
	TotalPass   int64          `json:"totalPass"`
	TotalFail   int64          `json:"totalFail"`
	TotalNone   int64          `json:"totalNone"`
	Tags        []string       `json:"tags"`
	Enabled     bool           `json:"enabled"`
	Cisid       []InsightCisID `json:"cisid"`
}

// ── Client methods ────────────────────────────────────────────────────────────

// ListInsights retrieves all insights.
func (c *Client) ListInsights(ctx context.Context) ([]Insight, error) {
	var result struct {
		ListInsights []Insight `json:"listInsights"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", listInsightsQuery, nil, &result); err != nil {
		return nil, fmt.Errorf("ListInsights: %w", err)
	}
	return result.ListInsights, nil
}

// UpdateInsightStatus updates a insight.
func (c *Client) UpdateInsightStatus(ctx context.Context, uuid string, enabled bool) (Insight, error) {
	vars := map[string]any{"uuid": uuid, "enabled": enabled}
	var result struct {
		UpdateInsightStatus Insight `json:"updateInsightStatus"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", updateInsightStatusMutation, vars, &result); err != nil {
		return Insight{}, fmt.Errorf("UpdateInsightStatus(%s): %w", uuid, err)
	}
	return result.UpdateInsightStatus, nil
}

// ListInsightComputers retrieves all insightComputers.
func (c *Client) ListInsightComputers(ctx context.Context, uuid string) ([]InsightComputer, error) {
	insightComputers, err := client.ListAll[InsightComputer](ctx, c.transport, "/app", listInsightComputersQuery, map[string]any{
		"filter":   nil,
		"order":    nil,
		"pageSize": 100,
		"uuid":     uuid,
	}, "listInsightComputers")
	if err != nil {
		return nil, fmt.Errorf("ListInsightComputers(%s): %w", uuid, err)
	}
	return insightComputers, nil
}

// GetFleetComplianceScore retrieves the complianceBaselineScore.
func (c *Client) GetFleetComplianceScore(ctx context.Context, date string) (ComplianceBaselineScore, error) {
	var vars map[string]any
	if date != "" {
		vars = map[string]any{"date": date}
	}
	var result struct {
		GetFleetComplianceScore ComplianceBaselineScore `json:"getFleetComplianceBaselineScore"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", getFleetComplianceScoreQuery, vars, &result); err != nil {
		return ComplianceBaselineScore{}, fmt.Errorf("GetFleetComplianceScore: %w", err)
	}
	return result.GetFleetComplianceScore, nil
}

func buildInsightVariables(input InsightInput) map[string]any {
	return map[string]any{
		"enabled": input.Enabled,
	}
}
