// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

// Code generated by tools/generate. DO NOT EDIT.

package jamfprotect

import (
	"context"
	"fmt"

	"github.com/Jamf-Concepts/jamfprotect-go-sdk/internal/client"
)

// ── Query/Mutation constants ──────────────────────────────────────────────────

const planFields = `
fragment PlanFields on Plan {
	id
	uuid
	hash
	name
	description
	created
	updated
	logLevel
	profileVersion
	autoUpdate
	threatPreventionStrategy
	customEngineConfig {
		MalwareRiskware
		AdversaryTactics
		SystemTampering
		FilelessThreats
		Experimental
	}
	commsConfig {
		fqdn
		protocol
	}
	infoSync {
		attrs
		insightsSyncInterval
	}
	signaturesFeedConfig {
		mode
	}
	actionConfigs {
		id
		name
	}
	exceptionSets {
		uuid
		name
		managed
	}
	usbControlSet {
		id
		name
	}
	telemetry {
		id
		name
	}
	telemetryV2 {
		id
		name
	}
	analyticSets {
		type
		analyticSet {
			uuid
			name
			managed
			analytics {
				uuid
				categories
			}
		}
	}
	unifiedLoggingFilterSets {
		uuid
		name
	}
}
`

const createPlanMutation = `
mutation createPlan($input: PlanInput!) {
	createPlan(input: $input) {
		...PlanFields
	}
}
` + planFields

const getPlanQuery = `
query getPlan($id: ID!) {
	getPlan(id: $id) {
		...PlanFields
	}
}
` + planFields

const updatePlanMutation = `
mutation updatePlan($id: ID!, $input: PlanInput!) {
	updatePlan(id: $id, input: $input) {
		...PlanFields
	}
}
` + planFields

const deletePlanMutation = `
mutation deletePlan($id: ID!) {
	deletePlan(id: $id) {
		id
	}
}
`

const listPlansQuery = `
query listPlans($nextToken: String, $direction: OrderDirection!, $field: PlanOrderField!, $filter: PlanFiltersInput, $pageSize: Int) {
	listPlans(
		input: {next: $nextToken, order: {direction: $direction, field: $field}, filter: $filter, pageSize: $pageSize}
	) {
		items {
			...PlanFields
		}
		pageInfo {
			next
			total
		}
	}
}
` + planFields

const getPlansConfigProfileQuery = `
query getPlansConfigProfile($id: ID!, $input: ProfileOptionsInput) {
	getPlansConfigProfile(id: $id, input: $input)
}
`

// ── Input types ───────────────────────────────────────────────────────────────

// PlanInput is the input for plan operations.
type PlanInput struct {
	ActionConfigs            string
	Description              string
	Name                     string
	LogLevel                 *string
	ExceptionSets            []string
	AnalyticSets             []PlanAnalyticSetInput
	UnifiedLoggingFilterSets []string
	Telemetry                *string
	TelemetryV2              *string
	TelemetryV2Null          bool
	AutoUpdate               bool
	InfoSync                 PlanInfoSyncInput
	CommsConfig              PlanCommsConfigInput
	SignaturesFeedConfig     PlanSignaturesFeedConfigInput
	USBControlSet            *string
	ThreatPreventionStrategy string
	CustomEngineConfig       *CustomEngineConfigInput
}

// PlanAnalyticSetInput is a nested input type.
type PlanAnalyticSetInput struct {
	UUID string `json:"uuid"`
	Type string `json:"type"`
}

// PlanInfoSyncInput is a nested input type.
type PlanInfoSyncInput struct {
	InfoSyncInterval     *int64   `json:"infoSyncInterval,omitempty"`
	InsightsSyncInterval int64    `json:"insightsSyncInterval"`
	Attrs                []string `json:"attrs"`
}

// PlanCommsConfigInput is a nested input type.
type PlanCommsConfigInput struct {
	FQDN     string `json:"fqdn"`
	Protocol string `json:"protocol"`
}

// PlanSignaturesFeedConfigInput is a nested input type.
type PlanSignaturesFeedConfigInput struct {
	Mode string `json:"mode"`
}

// CustomEngineConfigInput is a nested input type.
type CustomEngineConfigInput struct {
	MalwareRiskware  string `json:"MalwareRiskware"`
	AdversaryTactics string `json:"AdversaryTactics"`
	SystemTampering  string `json:"SystemTampering"`
	FilelessThreats  string `json:"FilelessThreats"`
	Experimental     string `json:"Experimental"`
}

// PlanConfigProfileOptionsInput is the input for planConfigProfileOptions operations.
type PlanConfigProfileOptionsInput struct {
	PPPC              bool
	Token             bool
	TokenOptions      PlanConfigProfileTokenOptionsInput
	CA                bool
	CSR               bool
	Websocket         bool
	Sign              bool
	SystemExtension   bool
	ServiceManagement bool
	ConfigVersion     *int64
}

// PlanConfigProfileTokenOptionsInput is a nested input type.
type PlanConfigProfileTokenOptionsInput struct {
	XPC              bool `json:"xpc"`
	KeychainClientID bool `json:"keychain_client_id"`
}

// ── Response types ────────────────────────────────────────────────────────────

// CustomEngineConfig contains CustomEngineConfig data.
type CustomEngineConfig struct {
	MalwareRiskware  string `json:"MalwareRiskware"`
	AdversaryTactics string `json:"AdversaryTactics"`
	SystemTampering  string `json:"SystemTampering"`
	FilelessThreats  string `json:"FilelessThreats"`
	Experimental     string `json:"Experimental"`
}

// PlanCommsConfig contains CommsConfig data.
type PlanCommsConfig struct {
	FQDN     string `json:"fqdn"`
	Protocol string `json:"protocol"`
}

// PlanInfoSync contains infoSync data.
type PlanInfoSync struct {
	Attrs                []string `json:"attrs"`
	InsightsSyncInterval int64    `json:"insightsSyncInterval"`
}

// PlanSignaturesFeed contains SignaturesFeedConfig data.
type PlanSignaturesFeed struct {
	Mode string `json:"mode"`
}

// PlanRef contains ActionConfigs data.
type PlanRef struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// PlanExceptionSet contains ExceptionSet data.
type PlanExceptionSet struct {
	UUID    string `json:"uuid"`
	Name    string `json:"name"`
	Managed bool   `json:"managed"`
}

// PlanAnalyticSet contains PlanAnalyticSet data.
type PlanAnalyticSet struct {
	Type        string             `json:"type"`
	AnalyticSet PlanAnalyticSetRef `json:"analyticSet"`
}

// PlanUnifiedLoggingFilterSet contains UnifiedLoggingFilterSet data.
type PlanUnifiedLoggingFilterSet struct {
	UUID string `json:"uuid"`
	Name string `json:"name"`
}

// PlanAnalyticSetRef contains AnalyticSet data.
type PlanAnalyticSetRef struct {
	UUID      string         `json:"uuid"`
	Name      string         `json:"name"`
	Managed   bool           `json:"managed"`
	Analytics []PlanAnalytic `json:"analytics"`
}

// PlanAnalytic contains Analytic data.
type PlanAnalytic struct {
	UUID       string   `json:"uuid"`
	Categories []string `json:"categories"`
}

// Plan represents a Jamf Protect plan.
type Plan struct {
	ID                       string                        `json:"id"`
	UUID                     string                        `json:"uuid"`
	Hash                     string                        `json:"hash"`
	Name                     string                        `json:"name"`
	Description              string                        `json:"description"`
	Created                  string                        `json:"created"`
	Updated                  string                        `json:"updated"`
	LogLevel                 string                        `json:"logLevel"`
	ProfileVersion           int64                         `json:"profileVersion"`
	AutoUpdate               bool                          `json:"autoUpdate"`
	ThreatPreventionStrategy string                        `json:"threatPreventionStrategy"`
	CustomEngineConfig       *CustomEngineConfig           `json:"customEngineConfig"`
	CommsConfig              *PlanCommsConfig              `json:"commsConfig"`
	InfoSync                 *PlanInfoSync                 `json:"infoSync"`
	SignaturesFeedConfig     *PlanSignaturesFeed           `json:"signaturesFeedConfig"`
	ActionConfigs            *PlanRef                      `json:"actionConfigs"`
	ExceptionSets            []PlanExceptionSet            `json:"exceptionSets"`
	USBControlSet            *PlanRef                      `json:"usbControlSet"`
	Telemetry                *PlanRef                      `json:"telemetry"`
	TelemetryV2              *PlanRef                      `json:"telemetryV2"`
	AnalyticSets             []PlanAnalyticSet             `json:"analyticSets"`
	UnifiedLoggingFilterSets []PlanUnifiedLoggingFilterSet `json:"unifiedLoggingFilterSets"`
}

// ── Client methods ────────────────────────────────────────────────────────────

// CreatePlan creates a new plan.
func (c *Client) CreatePlan(ctx context.Context, input PlanInput) (Plan, error) {
	vars := map[string]any{"input": buildPlanVariables(input)}
	var result struct {
		CreatePlan Plan `json:"createPlan"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", createPlanMutation, vars, &result); err != nil {
		return Plan{}, fmt.Errorf("CreatePlan: %w", err)
	}
	return result.CreatePlan, nil
}

// GetPlan retrieves a plan by ID.
func (c *Client) GetPlan(ctx context.Context, id string) (*Plan, error) {
	vars := map[string]any{"id": id}
	var result struct {
		GetPlan *Plan `json:"getPlan"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", getPlanQuery, vars, &result); err != nil {
		return nil, fmt.Errorf("GetPlan(%s): %w", id, err)
	}
	return result.GetPlan, nil
}

// UpdatePlan updates an existing plan.
func (c *Client) UpdatePlan(ctx context.Context, id string, input PlanInput) (Plan, error) {
	vars := map[string]any{"id": id, "input": buildPlanVariables(input)}
	var result struct {
		UpdatePlan Plan `json:"updatePlan"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", updatePlanMutation, vars, &result); err != nil {
		return Plan{}, fmt.Errorf("UpdatePlan(%s): %w", id, err)
	}
	return result.UpdatePlan, nil
}

// DeletePlan deletes a plan by ID.
func (c *Client) DeletePlan(ctx context.Context, id string) error {
	vars := map[string]any{"id": id}
	if err := c.transport.DoGraphQL(ctx, "/app", deletePlanMutation, vars, nil); err != nil {
		return fmt.Errorf("DeletePlan(%s): %w", id, err)
	}
	return nil
}

// ListPlans retrieves all plans.
func (c *Client) ListPlans(ctx context.Context) ([]Plan, error) {
	plans, err := client.ListAll[Plan](ctx, c.transport, "/app", listPlansQuery, map[string]any{
		"direction": "ASC",
		"field":     "created",
		"filter":    nil,
		"pageSize":  100,
	}, "listPlans")
	if err != nil {
		return nil, fmt.Errorf("ListPlans: %w", err)
	}
	return plans, nil
}

// GetPlansConfigProfile retrieves the string.
func (c *Client) GetPlansConfigProfile(ctx context.Context, id string, input *PlanConfigProfileOptionsInput) (string, error) {
	vars := map[string]any{"id": id}
	if input != nil {
		vars["input"] = buildPlanConfigProfileOptionsVariables(*input)
	}
	var result struct {
		GetPlansConfigProfile string `json:"getPlansConfigProfile"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", getPlansConfigProfileQuery, vars, &result); err != nil {
		return "", fmt.Errorf("GetPlansConfigProfile: %w", err)
	}
	return result.GetPlansConfigProfile, nil
}

func buildPlanVariables(input PlanInput) map[string]any {
	vars := map[string]any{
		"actionConfigs":        input.ActionConfigs,
		"description":          input.Description,
		"name":                 input.Name,
		"autoUpdate":           input.AutoUpdate,
		"infoSync":             input.InfoSync,
		"commsConfig":          input.CommsConfig,
		"signaturesFeedConfig": input.SignaturesFeedConfig,
	}
	if input.LogLevel != nil {
		vars["logLevel"] = *input.LogLevel
	}
	if input.ExceptionSets != nil {
		vars["exceptionSets"] = input.ExceptionSets
	}
	if input.AnalyticSets != nil {
		vars["analyticSets"] = input.AnalyticSets
	}
	if input.UnifiedLoggingFilterSets != nil {
		vars["unifiedLoggingFilterSets"] = input.UnifiedLoggingFilterSets
	}
	if input.Telemetry != nil {
		vars["telemetry"] = *input.Telemetry
	}
	if input.TelemetryV2Null {
		vars["telemetryV2"] = nil
	} else if input.TelemetryV2 != nil {
		vars["telemetryV2"] = *input.TelemetryV2
	}
	if input.USBControlSet != nil {
		vars["usbControlSet"] = *input.USBControlSet
	}
	if input.ThreatPreventionStrategy != "" {
		vars["threatPreventionStrategy"] = input.ThreatPreventionStrategy
	}
	if input.CustomEngineConfig != nil {
		vars["customEngineConfig"] = *input.CustomEngineConfig
	}
	return vars
}

func buildPlanConfigProfileOptionsVariables(input PlanConfigProfileOptionsInput) map[string]any {
	vars := map[string]any{
		"pppc":              input.PPPC,
		"token":             input.Token,
		"tokenOptions":      input.TokenOptions,
		"ca":                input.CA,
		"csr":               input.CSR,
		"websocket":         input.Websocket,
		"sign":              input.Sign,
		"systemExtension":   input.SystemExtension,
		"serviceManagement": input.ServiceManagement,
	}
	if input.ConfigVersion != nil {
		vars["configVersion"] = *input.ConfigVersion
	}
	return vars
}
