// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

// Code generated by tools/generate. DO NOT EDIT.

package jamfprotect

import (
	"context"
	"fmt"

	"github.com/Jamf-Concepts/jamfprotect-go-sdk/internal/client"
)

// ── Query/Mutation constants ──────────────────────────────────────────────────

const removableStorageControlSetFields = `
fragment RemovableStorageControlSetFields on USBControlSet {
	id
	name
	description
	defaultMountAction
	defaultMessageAction
	rules {
		mountAction
		messageAction
		type
		... on ProductRule {
			products {
				vendor
				product
			}
			applyTo
		}
		... on SerialRule {
			serials
			applyTo
		}
		... on VendorRule {
			vendors
			applyTo
		}
	}
	plans {
		id
		name
	}
	created
	updated
}
`

const createRemovableStorageControlSetMutation = `
mutation createUSBControlSet($name: String!, $description: String, $defaultMountAction: USBCONTROL_MOUNT_ACTION_TYPE_ENUM!, $defaultMessageAction: String, $rules: [USBControlRuleInput!]!) {
	createUSBControlSet(
		input: {name: $name, description: $description, defaultMountAction: $defaultMountAction, defaultMessageAction: $defaultMessageAction, rules: $rules}
	) {
		...RemovableStorageControlSetFields
	}
}
` + removableStorageControlSetFields

const getRemovableStorageControlSetQuery = `
query getUSBControlSet($id: ID!) {
	getUSBControlSet(id: $id) {
		...RemovableStorageControlSetFields
	}
}
` + removableStorageControlSetFields

const updateRemovableStorageControlSetMutation = `
mutation updateUSBControlSet($id: ID!, $name: String!, $description: String, $defaultMountAction: USBCONTROL_MOUNT_ACTION_TYPE_ENUM!, $defaultMessageAction: String, $rules: [USBControlRuleInput!]!) {
	updateUSBControlSet(
		id: $id
		input: {name: $name, description: $description, defaultMountAction: $defaultMountAction, defaultMessageAction: $defaultMessageAction, rules: $rules}
	) {
		...RemovableStorageControlSetFields
	}
}
` + removableStorageControlSetFields

const deleteRemovableStorageControlSetMutation = `
mutation deleteUSBControlSet($id: ID!) {
	deleteUSBControlSet(id: $id) {
		id
	}
}
`

const listRemovableStorageControlSetsQuery = `
query listUSBControlSets($nextToken: String, $direction: OrderDirection!, $field: USBControlOrderField!, $pageSize: Int) {
	listUSBControlSets(
		input: {next: $nextToken, order: {direction: $direction, field: $field}, pageSize: $pageSize}
	) {
		items {
			...RemovableStorageControlSetFields
		}
		pageInfo {
			next
			total
		}
	}
}
` + removableStorageControlSetFields

// ── Input types ───────────────────────────────────────────────────────────────

// RemovableStorageControlSetInput is the input for removableStorageControlSet operations.
type RemovableStorageControlSetInput struct {
	Name                 string
	Description          string
	DefaultMountAction   string
	DefaultMessageAction string
	Rules                []RemovableStorageControlRuleInput
}

// EncryptionRuleInput is a nested input type.
type EncryptionRuleInput struct {
	MountAction   string `json:"mountAction"`
	MessageAction string `json:"messageAction"`
}

// VendorRuleInput is a nested input type.
type VendorRuleInput struct {
	MountAction   string   `json:"mountAction"`
	MessageAction string   `json:"messageAction"`
	ApplyTo       string   `json:"applyTo"`
	Vendors       []string `json:"vendors"`
}

// SerialRuleInput is a nested input type.
type SerialRuleInput struct {
	MountAction   string   `json:"mountAction"`
	MessageAction string   `json:"messageAction"`
	ApplyTo       string   `json:"applyTo"`
	Serials       []string `json:"serials"`
}

// ProductValueInput is a nested input type.
type ProductValueInput struct {
	Vendor  string `json:"vendor"`
	Product string `json:"product"`
}

// ProductRuleInput is a nested input type.
type ProductRuleInput struct {
	MountAction   string              `json:"mountAction"`
	MessageAction string              `json:"messageAction"`
	ApplyTo       string              `json:"applyTo"`
	Products      []ProductValueInput `json:"products"`
}

// RemovableStorageControlRuleInput is a nested input type.
type RemovableStorageControlRuleInput struct {
	Type           string              `json:"type"`
	EncryptionRule EncryptionRuleInput `json:"encryptionRule"`
	VendorRule     VendorRuleInput     `json:"vendorRule"`
	SerialRule     SerialRuleInput     `json:"serialRule"`
	ProductRule    ProductRuleInput    `json:"productRule"`
}

// ── Response types ────────────────────────────────────────────────────────────

// RemovableStorageControlRule contains USBControlRule data.
type RemovableStorageControlRule struct {
	MountAction   string                               `json:"mountAction"`
	MessageAction string                               `json:"messageAction"`
	Type          string                               `json:"type"`
	Products      []RemovableStorageControlProductPair `json:"products"`
	ApplyTo       string                               `json:"applyTo"`
	Serials       []string                             `json:"serials"`
	Vendors       []string                             `json:"vendors"`
}

// RemovableStorageControlProductPair contains ProductValue data.
type RemovableStorageControlProductPair struct {
	Vendor  string `json:"vendor"`
	Product string `json:"product"`
}

// RemovableStorageControlSetPlan contains Plan data.
type RemovableStorageControlSetPlan struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// RemovableStorageControlSet represents a Jamf Protect removableStorageControlSet.
type RemovableStorageControlSet struct {
	ID                   string                           `json:"id"`
	Name                 string                           `json:"name"`
	Description          string                           `json:"description"`
	DefaultMountAction   string                           `json:"defaultMountAction"`
	DefaultMessageAction string                           `json:"defaultMessageAction"`
	Rules                []RemovableStorageControlRule    `json:"rules"`
	Plans                []RemovableStorageControlSetPlan `json:"plans"`
	Created              string                           `json:"created"`
	Updated              string                           `json:"updated"`
}

// ── Client methods ────────────────────────────────────────────────────────────

// CreateRemovableStorageControlSet creates a new removableStorageControlSet.
func (c *Client) CreateRemovableStorageControlSet(ctx context.Context, input RemovableStorageControlSetInput) (RemovableStorageControlSet, error) {
	vars := buildRemovableStorageControlSetVariables(input)
	var result struct {
		CreateRemovableStorageControlSet RemovableStorageControlSet `json:"createUSBControlSet"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", createRemovableStorageControlSetMutation, vars, &result); err != nil {
		return RemovableStorageControlSet{}, fmt.Errorf("CreateRemovableStorageControlSet: %w", err)
	}
	return result.CreateRemovableStorageControlSet, nil
}

// GetRemovableStorageControlSet retrieves a removableStorageControlSet by ID.
func (c *Client) GetRemovableStorageControlSet(ctx context.Context, id string) (*RemovableStorageControlSet, error) {
	vars := map[string]any{"id": id}
	var result struct {
		GetRemovableStorageControlSet *RemovableStorageControlSet `json:"getUSBControlSet"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", getRemovableStorageControlSetQuery, vars, &result); err != nil {
		return nil, fmt.Errorf("GetRemovableStorageControlSet(%s): %w", id, err)
	}
	return result.GetRemovableStorageControlSet, nil
}

// UpdateRemovableStorageControlSet updates an existing removableStorageControlSet.
func (c *Client) UpdateRemovableStorageControlSet(ctx context.Context, id string, input RemovableStorageControlSetInput) (RemovableStorageControlSet, error) {
	vars := buildRemovableStorageControlSetVariables(input)
	vars["id"] = id
	var result struct {
		UpdateRemovableStorageControlSet RemovableStorageControlSet `json:"updateUSBControlSet"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", updateRemovableStorageControlSetMutation, vars, &result); err != nil {
		return RemovableStorageControlSet{}, fmt.Errorf("UpdateRemovableStorageControlSet(%s): %w", id, err)
	}
	return result.UpdateRemovableStorageControlSet, nil
}

// DeleteRemovableStorageControlSet deletes a removableStorageControlSet by ID.
func (c *Client) DeleteRemovableStorageControlSet(ctx context.Context, id string) error {
	vars := map[string]any{"id": id}
	if err := c.transport.DoGraphQL(ctx, "/app", deleteRemovableStorageControlSetMutation, vars, nil); err != nil {
		return fmt.Errorf("DeleteRemovableStorageControlSet(%s): %w", id, err)
	}
	return nil
}

// ListRemovableStorageControlSets retrieves all removableStorageControlSets.
func (c *Client) ListRemovableStorageControlSets(ctx context.Context) ([]RemovableStorageControlSet, error) {
	removableStorageControlSets, err := client.ListAll[RemovableStorageControlSet](ctx, c.transport, "/app", listRemovableStorageControlSetsQuery, map[string]any{
		"direction": "ASC",
		"field":     "created",
		"pageSize":  100,
	}, "listUSBControlSets")
	if err != nil {
		return nil, fmt.Errorf("ListRemovableStorageControlSets: %w", err)
	}
	return removableStorageControlSets, nil
}

func buildRemovableStorageControlSetVariables(input RemovableStorageControlSetInput) map[string]any {
	return map[string]any{
		"name":                 input.Name,
		"description":          input.Description,
		"defaultMountAction":   input.DefaultMountAction,
		"defaultMessageAction": input.DefaultMessageAction,
		"rules":                input.Rules,
	}
}
