// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

// Code generated by tools/generate. DO NOT EDIT.

package jamfprotect

import (
	"context"
	"fmt"

	"github.com/Jamf-Concepts/jamfprotect-go-sdk/internal/client"
)

// ── Query/Mutation constants ──────────────────────────────────────────────────

const telemetryV2Fields = `
fragment TelemetryV2Fields on TelemetryV2 {
	id
	name
	description
	created
	updated
	logFiles
	logFileCollection
	performanceMetrics
	plans @include(if: $RBAC_Plan) {
		id
		name
	}
	events
	fileHashing
}
`

const createTelemetryV2Mutation = `
mutation createTelemetryV2($input: TelemetryInputV2!, $RBAC_Plan: Boolean!) {
	createTelemetryV2(input: $input) {
		...TelemetryV2Fields
	}
}
` + telemetryV2Fields

const getTelemetryV2Query = `
query getTelemetryV2($id: ID!, $RBAC_Plan: Boolean!) {
	getTelemetryV2(id: $id) {
		...TelemetryV2Fields
	}
}
` + telemetryV2Fields

const updateTelemetryV2Mutation = `
mutation updateTelemetryV2($id: ID!, $input: TelemetryInputV2!, $RBAC_Plan: Boolean!) {
	updateTelemetryV2(id: $id, input: $input) {
		...TelemetryV2Fields
	}
}
` + telemetryV2Fields

const deleteTelemetryV2Mutation = `
mutation deleteTelemetryV2($id: ID!) {
	deleteTelemetryV2(id: $id) {
		id
	}
}
`

const listTelemetriesV2Query = `
query listTelemetriesV2($nextToken: String, $direction: OrderDirection!, $field: TelemetryOrderField!, $pageSize: Int, $RBAC_Plan: Boolean!) {
	listTelemetriesV2(
		input: {next: $nextToken, order: {direction: $direction, field: $field}, pageSize: $pageSize}
	) {
		items {
			...TelemetryV2Fields
		}
		pageInfo {
			next
			total
		}
	}
}
` + telemetryV2Fields

// ── Input types ───────────────────────────────────────────────────────────────

// TelemetryV2Input is the input for telemetryV2 operations.
type TelemetryV2Input struct {
	Name               string
	Description        string
	LogFiles           []string
	LogFileCollection  bool
	PerformanceMetrics bool
	Events             []string
	FileHashing        bool
}

// ── Response types ────────────────────────────────────────────────────────────

// TelemetryV2Plan contains Plan data.
type TelemetryV2Plan struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// TelemetryV2 represents a Jamf Protect telemetryV2.
type TelemetryV2 struct {
	ID                 string            `json:"id"`
	Name               string            `json:"name"`
	Description        string            `json:"description"`
	Created            string            `json:"created"`
	Updated            string            `json:"updated"`
	LogFiles           []string          `json:"logFiles"`
	LogFileCollection  bool              `json:"logFileCollection"`
	PerformanceMetrics bool              `json:"performanceMetrics"`
	Plans              []TelemetryV2Plan `json:"plans"`
	Events             []string          `json:"events"`
	FileHashing        bool              `json:"fileHashing"`
}

// ── Client methods ────────────────────────────────────────────────────────────

// CreateTelemetryV2 creates a new telemetryV2.
func (c *Client) CreateTelemetryV2(ctx context.Context, input TelemetryV2Input) (TelemetryV2, error) {
	vars := mergeVars(map[string]any{"input": buildTelemetryV2Variables(input)}, rbacPlan)
	var result struct {
		CreateTelemetryV2 TelemetryV2 `json:"createTelemetryV2"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", createTelemetryV2Mutation, vars, &result); err != nil {
		return TelemetryV2{}, fmt.Errorf("CreateTelemetryV2: %w", err)
	}
	return result.CreateTelemetryV2, nil
}

// GetTelemetryV2 retrieves a telemetryV2 by ID.
func (c *Client) GetTelemetryV2(ctx context.Context, id string) (*TelemetryV2, error) {
	vars := mergeVars(map[string]any{"id": id}, rbacPlan)
	var result struct {
		GetTelemetryV2 *TelemetryV2 `json:"getTelemetryV2"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", getTelemetryV2Query, vars, &result); err != nil {
		return nil, fmt.Errorf("GetTelemetryV2(%s): %w", id, err)
	}
	return result.GetTelemetryV2, nil
}

// UpdateTelemetryV2 updates an existing telemetryV2.
func (c *Client) UpdateTelemetryV2(ctx context.Context, id string, input TelemetryV2Input) (TelemetryV2, error) {
	vars := mergeVars(map[string]any{"id": id, "input": buildTelemetryV2Variables(input)}, rbacPlan)
	var result struct {
		UpdateTelemetryV2 TelemetryV2 `json:"updateTelemetryV2"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", updateTelemetryV2Mutation, vars, &result); err != nil {
		return TelemetryV2{}, fmt.Errorf("UpdateTelemetryV2(%s): %w", id, err)
	}
	return result.UpdateTelemetryV2, nil
}

// DeleteTelemetryV2 deletes a telemetryV2 by ID.
func (c *Client) DeleteTelemetryV2(ctx context.Context, id string) error {
	vars := map[string]any{"id": id}
	if err := c.transport.DoGraphQL(ctx, "/app", deleteTelemetryV2Mutation, vars, nil); err != nil {
		return fmt.Errorf("DeleteTelemetryV2(%s): %w", id, err)
	}
	return nil
}

// ListTelemetriesV2 retrieves all telemetryV2s.
func (c *Client) ListTelemetriesV2(ctx context.Context) ([]TelemetryV2, error) {
	telemetryV2s, err := client.ListAll[TelemetryV2](ctx, c.transport, "/app", listTelemetriesV2Query, mergeVars(map[string]any{
		"direction": "DESC",
		"field":     "created",
		"pageSize":  100,
	}, rbacPlan), "listTelemetriesV2")
	if err != nil {
		return nil, fmt.Errorf("ListTelemetriesV2: %w", err)
	}
	return telemetryV2s, nil
}

func buildTelemetryV2Variables(input TelemetryV2Input) map[string]any {
	return map[string]any{
		"name":               input.Name,
		"description":        input.Description,
		"logFiles":           input.LogFiles,
		"logFileCollection":  input.LogFileCollection,
		"performanceMetrics": input.PerformanceMetrics,
		"events":             input.Events,
		"fileHashing":        input.FileHashing,
	}
}
