// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

// Code generated by tools/generate. DO NOT EDIT.

package jamfprotect

import (
	"context"
	"fmt"

	"github.com/Jamf-Concepts/jamfprotect-go-sdk/internal/client"
)

// ── Query/Mutation constants ──────────────────────────────────────────────────

const unifiedLoggingFilterFields = `
fragment UnifiedLoggingFilterFields on UnifiedLoggingFilter {
	uuid
	name
	description
	created
	updated
	filter
	tags
	enabled
}
`

const getUnifiedLoggingFilterQuery = `
query getUnifiedLoggingFilter($uuid: ID!) {
	getUnifiedLoggingFilter(uuid: $uuid) {
		...UnifiedLoggingFilterFields
	}
}
` + unifiedLoggingFilterFields

const createUnifiedLoggingFilterMutation = `
mutation createUnifiedLoggingFilter($name: String!, $description: String, $filter: String!, $tags: [String]!, $enabled: Boolean) {
	createUnifiedLoggingFilter(
		input: {name: $name, description: $description, filter: $filter, tags: $tags, enabled: $enabled}
	) {
		...UnifiedLoggingFilterFields
	}
}
` + unifiedLoggingFilterFields

const updateUnifiedLoggingFilterMutation = `
mutation updateUnifiedLoggingFilter($uuid: ID!, $name: String!, $description: String, $filter: String!, $tags: [String]!, $enabled: Boolean) {
	updateUnifiedLoggingFilter(
		uuid: $uuid
		input: {name: $name, description: $description, filter: $filter, tags: $tags, enabled: $enabled}
	) {
		...UnifiedLoggingFilterFields
	}
}
` + unifiedLoggingFilterFields

const deleteUnifiedLoggingFilterMutation = `
mutation deleteUnifiedLoggingFilter($uuid: ID!) {
	deleteUnifiedLoggingFilter(uuid: $uuid) {
		uuid
	}
}
`

const listUnifiedLoggingFiltersQuery = `
query listUnifiedLoggingFilters($nextToken: String, $direction: OrderDirection!, $field: UnifiedLoggingFiltersOrderField!, $pageSize: Int, $filter: UnifiedLoggingFiltersFilterInput) {
	listUnifiedLoggingFilters(
		input: {next: $nextToken, order: {direction: $direction, field: $field}, pageSize: $pageSize, filter: $filter}
	) {
		items {
			...UnifiedLoggingFilterFields
		}
		pageInfo {
			next
			total
		}
	}
}
` + unifiedLoggingFilterFields

// ── Input types ───────────────────────────────────────────────────────────────

// UnifiedLoggingFilterInput is the input for unifiedLoggingFilter operations.
type UnifiedLoggingFilterInput struct {
	Name        string
	Description string
	Filter      string
	Tags        []string
	Enabled     bool
}

// ── Response types ────────────────────────────────────────────────────────────

// UnifiedLoggingFilter represents a Jamf Protect unifiedLoggingFilter.
type UnifiedLoggingFilter struct {
	UUID        string   `json:"uuid"`
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Created     string   `json:"created"`
	Updated     string   `json:"updated"`
	Filter      string   `json:"filter"`
	Tags        []string `json:"tags"`
	Enabled     bool     `json:"enabled"`
}

// ── Client methods ────────────────────────────────────────────────────────────

// GetUnifiedLoggingFilter retrieves a unifiedLoggingFilter by ID.
func (c *Client) GetUnifiedLoggingFilter(ctx context.Context, uuid string) (*UnifiedLoggingFilter, error) {
	vars := map[string]any{"uuid": uuid}
	var result struct {
		GetUnifiedLoggingFilter *UnifiedLoggingFilter `json:"getUnifiedLoggingFilter"`
	}
	if err := c.transport.DoGraphQL(ctx, "/graphql", getUnifiedLoggingFilterQuery, vars, &result); err != nil {
		return nil, fmt.Errorf("GetUnifiedLoggingFilter(%s): %w", uuid, err)
	}
	return result.GetUnifiedLoggingFilter, nil
}

// CreateUnifiedLoggingFilter creates a new unifiedLoggingFilter.
func (c *Client) CreateUnifiedLoggingFilter(ctx context.Context, input UnifiedLoggingFilterInput) (UnifiedLoggingFilter, error) {
	vars := buildUnifiedLoggingFilterVariables(input)
	var result struct {
		CreateUnifiedLoggingFilter UnifiedLoggingFilter `json:"createUnifiedLoggingFilter"`
	}
	if err := c.transport.DoGraphQL(ctx, "/graphql", createUnifiedLoggingFilterMutation, vars, &result); err != nil {
		return UnifiedLoggingFilter{}, fmt.Errorf("CreateUnifiedLoggingFilter: %w", err)
	}
	return result.CreateUnifiedLoggingFilter, nil
}

// UpdateUnifiedLoggingFilter updates an existing unifiedLoggingFilter.
func (c *Client) UpdateUnifiedLoggingFilter(ctx context.Context, uuid string, input UnifiedLoggingFilterInput) (UnifiedLoggingFilter, error) {
	vars := buildUnifiedLoggingFilterVariables(input)
	vars["uuid"] = uuid
	var result struct {
		UpdateUnifiedLoggingFilter UnifiedLoggingFilter `json:"updateUnifiedLoggingFilter"`
	}
	if err := c.transport.DoGraphQL(ctx, "/graphql", updateUnifiedLoggingFilterMutation, vars, &result); err != nil {
		return UnifiedLoggingFilter{}, fmt.Errorf("UpdateUnifiedLoggingFilter(%s): %w", uuid, err)
	}
	return result.UpdateUnifiedLoggingFilter, nil
}

// DeleteUnifiedLoggingFilter deletes a unifiedLoggingFilter by ID.
func (c *Client) DeleteUnifiedLoggingFilter(ctx context.Context, uuid string) error {
	vars := map[string]any{"uuid": uuid}
	if err := c.transport.DoGraphQL(ctx, "/graphql", deleteUnifiedLoggingFilterMutation, vars, nil); err != nil {
		return fmt.Errorf("DeleteUnifiedLoggingFilter(%s): %w", uuid, err)
	}
	return nil
}

// ListUnifiedLoggingFilters retrieves all unifiedLoggingFilters.
func (c *Client) ListUnifiedLoggingFilters(ctx context.Context) ([]UnifiedLoggingFilter, error) {
	unifiedLoggingFilters, err := client.ListAll[UnifiedLoggingFilter](ctx, c.transport, "/graphql", listUnifiedLoggingFiltersQuery, map[string]any{
		"direction": "ASC",
		"field":     "name",
		"filter":    map[string]any{},
		"pageSize":  100,
	}, "listUnifiedLoggingFilters")
	if err != nil {
		return nil, fmt.Errorf("ListUnifiedLoggingFilters: %w", err)
	}
	return unifiedLoggingFilters, nil
}

func buildUnifiedLoggingFilterVariables(input UnifiedLoggingFilterInput) map[string]any {
	return map[string]any{
		"name":        input.Name,
		"description": input.Description,
		"filter":      input.Filter,
		"tags":        input.Tags,
		"enabled":     input.Enabled,
	}
}
