// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

// Code generated by tools/generate. DO NOT EDIT.

package jamfprotect

import (
	"context"
	"fmt"

	"github.com/Jamf-Concepts/jamfprotect-go-sdk/internal/client"
)

// ── Query/Mutation constants ──────────────────────────────────────────────────

const unifiedLoggingFilterSetFields = `
fragment UnifiedLoggingFilterSetFields on UnifiedLoggingFilterSet {
	uuid
	name
	description
	created
	updated
	filters {
		uuid
		name
	}
	plans {
		id
		name
	}
}
`

const getUnifiedLoggingFilterSetQuery = `
query getUnifiedLoggingFilterSet($uuid: ID!) {
	getUnifiedLoggingFilterSet(uuid: $uuid) {
		...UnifiedLoggingFilterSetFields
	}
}
` + unifiedLoggingFilterSetFields

const createUnifiedLoggingFilterSetMutation = `
mutation createUnifiedLoggingFilterSet($name: String!, $description: String, $filters: [ID!]!) {
	createUnifiedLoggingFilterSet(
		input: {name: $name, description: $description, filters: $filters}
	) {
		...UnifiedLoggingFilterSetFields
	}
}
` + unifiedLoggingFilterSetFields

const updateUnifiedLoggingFilterSetMutation = `
mutation updateUnifiedLoggingFilterSet($uuid: ID!, $name: String!, $description: String, $filters: [ID!]!) {
	updateUnifiedLoggingFilterSet(
		uuid: $uuid
		input: {name: $name, description: $description, filters: $filters}
	) {
		...UnifiedLoggingFilterSetFields
	}
}
` + unifiedLoggingFilterSetFields

const deleteUnifiedLoggingFilterSetMutation = `
mutation deleteUnifiedLoggingFilterSet($uuid: ID!) {
	deleteUnifiedLoggingFilterSet(uuid: $uuid) {
		uuid
	}
}
`

const listUnifiedLoggingFilterSetsQuery = `
query listUnifiedLoggingFilterSets($nextToken: String, $direction: OrderDirection!, $field: UnifiedLoggingFilterSetOrderField!, $filter: UnifiedLoggingFilterSetFiltersInput, $pageSize: Int) {
	listUnifiedLoggingFilterSets(
		input: {next: $nextToken, order: {direction: $direction, field: $field}, filter: $filter, pageSize: $pageSize}
	) {
		items {
			...UnifiedLoggingFilterSetFields
		}
		pageInfo {
			next
			total
		}
	}
}
` + unifiedLoggingFilterSetFields

// ── Input types ───────────────────────────────────────────────────────────────

// UnifiedLoggingFilterSetInput is the input for unifiedLoggingFilterSet operations.
type UnifiedLoggingFilterSetInput struct {
	Name        string
	Description string
	Filters     []string
}

// ── Response types ────────────────────────────────────────────────────────────

// UnifiedLoggingFilterSetFilter contains UnifiedLoggingFilter data.
type UnifiedLoggingFilterSetFilter struct {
	UUID string `json:"uuid"`
	Name string `json:"name"`
}

// UnifiedLoggingFilterSetPlan contains Plan data.
type UnifiedLoggingFilterSetPlan struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// UnifiedLoggingFilterSet represents a Jamf Protect unifiedLoggingFilterSet.
type UnifiedLoggingFilterSet struct {
	UUID        string                          `json:"uuid"`
	Name        string                          `json:"name"`
	Description string                          `json:"description"`
	Created     string                          `json:"created"`
	Updated     string                          `json:"updated"`
	Filters     []UnifiedLoggingFilterSetFilter `json:"filters"`
	Plans       []UnifiedLoggingFilterSetPlan   `json:"plans"`
}

// ── Client methods ────────────────────────────────────────────────────────────

// GetUnifiedLoggingFilterSet retrieves a unifiedLoggingFilterSet by ID.
func (c *Client) GetUnifiedLoggingFilterSet(ctx context.Context, uuid string) (*UnifiedLoggingFilterSet, error) {
	vars := map[string]any{"uuid": uuid}
	var result struct {
		GetUnifiedLoggingFilterSet *UnifiedLoggingFilterSet `json:"getUnifiedLoggingFilterSet"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", getUnifiedLoggingFilterSetQuery, vars, &result); err != nil {
		return nil, fmt.Errorf("GetUnifiedLoggingFilterSet(%s): %w", uuid, err)
	}
	return result.GetUnifiedLoggingFilterSet, nil
}

// CreateUnifiedLoggingFilterSet creates a new unifiedLoggingFilterSet.
func (c *Client) CreateUnifiedLoggingFilterSet(ctx context.Context, input UnifiedLoggingFilterSetInput) (UnifiedLoggingFilterSet, error) {
	vars := buildUnifiedLoggingFilterSetVariables(input)
	var result struct {
		CreateUnifiedLoggingFilterSet UnifiedLoggingFilterSet `json:"createUnifiedLoggingFilterSet"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", createUnifiedLoggingFilterSetMutation, vars, &result); err != nil {
		return UnifiedLoggingFilterSet{}, fmt.Errorf("CreateUnifiedLoggingFilterSet: %w", err)
	}
	return result.CreateUnifiedLoggingFilterSet, nil
}

// UpdateUnifiedLoggingFilterSet updates an existing unifiedLoggingFilterSet.
func (c *Client) UpdateUnifiedLoggingFilterSet(ctx context.Context, uuid string, input UnifiedLoggingFilterSetInput) (UnifiedLoggingFilterSet, error) {
	vars := buildUnifiedLoggingFilterSetVariables(input)
	vars["uuid"] = uuid
	var result struct {
		UpdateUnifiedLoggingFilterSet UnifiedLoggingFilterSet `json:"updateUnifiedLoggingFilterSet"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", updateUnifiedLoggingFilterSetMutation, vars, &result); err != nil {
		return UnifiedLoggingFilterSet{}, fmt.Errorf("UpdateUnifiedLoggingFilterSet(%s): %w", uuid, err)
	}
	return result.UpdateUnifiedLoggingFilterSet, nil
}

// DeleteUnifiedLoggingFilterSet deletes a unifiedLoggingFilterSet by ID.
func (c *Client) DeleteUnifiedLoggingFilterSet(ctx context.Context, uuid string) error {
	vars := map[string]any{"uuid": uuid}
	if err := c.transport.DoGraphQL(ctx, "/app", deleteUnifiedLoggingFilterSetMutation, vars, nil); err != nil {
		return fmt.Errorf("DeleteUnifiedLoggingFilterSet(%s): %w", uuid, err)
	}
	return nil
}

// ListUnifiedLoggingFilterSets retrieves all unifiedLoggingFilterSets.
func (c *Client) ListUnifiedLoggingFilterSets(ctx context.Context) ([]UnifiedLoggingFilterSet, error) {
	unifiedLoggingFilterSets, err := client.ListAll[UnifiedLoggingFilterSet](ctx, c.transport, "/app", listUnifiedLoggingFilterSetsQuery, map[string]any{
		"direction": "ASC",
		"field":     "name",
		"filter":    map[string]any{},
		"pageSize":  100,
	}, "listUnifiedLoggingFilterSets")
	if err != nil {
		return nil, fmt.Errorf("ListUnifiedLoggingFilterSets: %w", err)
	}
	return unifiedLoggingFilterSets, nil
}

func buildUnifiedLoggingFilterSetVariables(input UnifiedLoggingFilterSetInput) map[string]any {
	return map[string]any{
		"name":        input.Name,
		"description": input.Description,
		"filters":     input.Filters,
	}
}
