// Copyright Jamf Software LLC 2026
// SPDX-License-Identifier: MIT

// Code generated by tools/generate. DO NOT EDIT.

package jamfprotect

import (
	"context"
	"fmt"

	"github.com/Jamf-Concepts/jamfprotect-go-sdk/internal/client"
)

// ── Query/Mutation constants ──────────────────────────────────────────────────

const userFields = `
fragment UserFields on User {
	id
	email
	sub @skip(if: $hasLimitedAppAccess)
	connection @include(if: $RBAC_Connection) {
		id
		name
		requireKnownUsers
		source
	}
	assignedRoles @skip(if: $hasLimitedAppAccess) @include(if: $RBAC_Role) {
		id
		name
	}
	assignedGroups @skip(if: $hasLimitedAppAccess) @include(if: $RBAC_Group) {
		id
		name
		assignedRoles @include(if: $RBAC_Role) {
			id
			name
		}
	}
	lastLogin
	source @skip(if: $hasLimitedAppAccess)
	receiveEmailAlert
	emailAlertMinSeverity
	extraAttrs @skip(if: $hasLimitedAppAccess)
	created
	updated
}
`

const createUserMutation = `
mutation createUser($email: AWSEmail!, $connectionId: ID, $roleIds: [ID], $groupIds: [ID], $receiveEmailAlert: Boolean!, $emailAlertMinSeverity: SEVERITY, $RBAC_Connection: Boolean!, $RBAC_Group: Boolean!, $RBAC_Role: Boolean!, $hasLimitedAppAccess: Boolean!) {
	createUser(
		input: {email: $email, connectionId: $connectionId, roleIds: $roleIds, groupIds: $groupIds, receiveEmailAlert: $receiveEmailAlert, emailAlertMinSeverity: $emailAlertMinSeverity}
	) {
		...UserFields
	}
}
` + userFields

const getUserQuery = `
query getUser($id: ID!, $RBAC_Connection: Boolean!, $RBAC_Group: Boolean!, $RBAC_Role: Boolean!, $hasLimitedAppAccess: Boolean!) {
	getUser(id: $id) {
		...UserFields
	}
}
` + userFields

const updateUserMutation = `
mutation updateUser($id: ID!, $roleIds: [ID], $groupIds: [ID], $receiveEmailAlert: Boolean!, $emailAlertMinSeverity: SEVERITY, $RBAC_Connection: Boolean!, $RBAC_Group: Boolean!, $RBAC_Role: Boolean!, $hasLimitedAppAccess: Boolean!) {
	updateUser(
		id: $id
		input: {roleIds: $roleIds, groupIds: $groupIds, receiveEmailAlert: $receiveEmailAlert, emailAlertMinSeverity: $emailAlertMinSeverity}
	) {
		...UserFields
	}
}
` + userFields

const deleteUserMutation = `
mutation deleteUser($id: ID!) {
	deleteUser(id: $id) {
		id
	}
}
`

const listUsersQuery = `
query listUsers($nextToken: String, $direction: OrderDirection!, $field: UserOrderField!, $pageSize: Int, $RBAC_Connection: Boolean!, $RBAC_Group: Boolean!, $RBAC_Role: Boolean!, $hasLimitedAppAccess: Boolean!) {
	listUsers(
		input: {next: $nextToken, order: {direction: $direction, field: $field}, pageSize: $pageSize}
	) {
		items {
			...UserFields
		}
		pageInfo {
			next
			total
		}
	}
}
` + userFields

// ── Input types ───────────────────────────────────────────────────────────────

// UserInput is the input for user operations.
type UserInput struct {
	Email                 string
	ConnectionID          *string
	RoleIDs               []string
	GroupIDs              []string
	ReceiveEmailAlert     bool
	EmailAlertMinSeverity string
}

// ── Response types ────────────────────────────────────────────────────────────

// UserConnection contains Connection data.
type UserConnection struct {
	ID                string `json:"id"`
	Name              string `json:"name"`
	RequireKnownUsers bool   `json:"requireKnownUsers"`
	Source            string `json:"source"`
}

// UserRole contains Role data.
type UserRole struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// UserGroup contains Group data.
type UserGroup struct {
	ID            string     `json:"id"`
	Name          string     `json:"name"`
	AssignedRoles []UserRole `json:"assignedRoles"`
}

// User represents a Jamf Protect user.
type User struct {
	ID                    string          `json:"id"`
	Email                 string          `json:"email"`
	Sub                   *string         `json:"sub"`
	Connection            *UserConnection `json:"connection"`
	AssignedRoles         []UserRole      `json:"assignedRoles"`
	AssignedGroups        []UserGroup     `json:"assignedGroups"`
	LastLogin             *string         `json:"lastLogin"`
	Source                string          `json:"source"`
	ReceiveEmailAlert     bool            `json:"receiveEmailAlert"`
	EmailAlertMinSeverity string          `json:"emailAlertMinSeverity"`
	ExtraAttrs            string          `json:"extraAttrs"`
	Created               string          `json:"created"`
	Updated               string          `json:"updated"`
}

// ── Client methods ────────────────────────────────────────────────────────────

// CreateUser creates a new user.
func (c *Client) CreateUser(ctx context.Context, input UserInput) (User, error) {
	vars := mergeVars(buildUserVariables(input), map[string]any{"hasLimitedAppAccess": false}, rbacUser)
	var result struct {
		CreateUser User `json:"createUser"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", createUserMutation, vars, &result); err != nil {
		return User{}, fmt.Errorf("CreateUser: %w", err)
	}
	return result.CreateUser, nil
}

// GetUser retrieves a user by ID.
func (c *Client) GetUser(ctx context.Context, id string) (*User, error) {
	vars := mergeVars(map[string]any{"id": id}, map[string]any{"hasLimitedAppAccess": false}, rbacUser)
	var result struct {
		GetUser *User `json:"getUser"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", getUserQuery, vars, &result); err != nil {
		return nil, fmt.Errorf("GetUser(%s): %w", id, err)
	}
	return result.GetUser, nil
}

// UpdateUser updates an existing user.
func (c *Client) UpdateUser(ctx context.Context, id string, input UserInput) (User, error) {
	vars := mergeVars(buildUserVariables(input), map[string]any{"hasLimitedAppAccess": false}, rbacUser)
	vars["id"] = id
	var result struct {
		UpdateUser User `json:"updateUser"`
	}
	if err := c.transport.DoGraphQL(ctx, "/app", updateUserMutation, vars, &result); err != nil {
		return User{}, fmt.Errorf("UpdateUser(%s): %w", id, err)
	}
	return result.UpdateUser, nil
}

// DeleteUser deletes a user by ID.
func (c *Client) DeleteUser(ctx context.Context, id string) error {
	vars := map[string]any{"id": id}
	if err := c.transport.DoGraphQL(ctx, "/app", deleteUserMutation, vars, nil); err != nil {
		return fmt.Errorf("DeleteUser(%s): %w", id, err)
	}
	return nil
}

// ListUsers retrieves all users.
func (c *Client) ListUsers(ctx context.Context) ([]User, error) {
	users, err := client.ListAll[User](ctx, c.transport, "/app", listUsersQuery, mergeVars(map[string]any{
		"direction":           "ASC",
		"field":               "email",
		"hasLimitedAppAccess": false,
		"pageSize":            100,
	}, rbacUser), "listUsers")
	if err != nil {
		return nil, fmt.Errorf("ListUsers: %w", err)
	}
	return users, nil
}

func buildUserVariables(input UserInput) map[string]any {
	vars := map[string]any{
		"connectionId":          input.ConnectionID,
		"roleIds":               input.RoleIDs,
		"groupIds":              input.GroupIDs,
		"receiveEmailAlert":     input.ReceiveEmailAlert,
		"emailAlertMinSeverity": input.EmailAlertMinSeverity,
	}
	if input.Email != "" {
		vars["email"] = input.Email
	}
	return vars
}
